### ISSUE TITLE
implicit form labels

### ISSUE THREAD

**Issue by kengdoj** [w3c/html-aam#102]
Are implicit labels included in the INPUT type=text accessible name calculation?

[5.1.1](http://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-search-input-type-tel-input-type-url-and-textarea-element): 

> 2.Otherwise use the associated label element(s) accessible name(s)...

For example:
```
<label>
  First name:
  <input type="text" name="firstname">
</label>
```

Thank you in advance for the clarification.

**Comment by jasonkiss** [comment]
Whether an `input` is associated with a `label` element via `for` and `id` attributes or by being nested within the `label` element, the `label` is used in computing the `input`'s accessible name.
