### ISSUE TITLE
The <form> element should only map to FORM landmark with restriction of accessible name

### ISSUE THREAD

**Issue by jongund** [w3c/html-aam#106]
The following condition should be added for the form element to become a form landmark:

"The form role if the form element has an accessible name. Otherwise, no corresponding role."

This is the similar to the section element becoming a region landmark requirement.

This is important since many frameworks including .NET wrap an entire web page in a FORM element, obviously not very functional as a landmark.

**Comment by joanmarie** [comment]
As I [commented on the pull request](https://github.com/w3c/html-aam/pull/107#issuecomment-335415667) which was merged earlier today, I think some additional changes may be called for: The merged modification does accomplish what is described in the summary for this issue, namely only map named `form` elements as landmarks (via using the ARIA mappings). BUT they don't state what the mappings should be for `form` elements without names.

**Comment by jongund** [comment]
Steve,
Thanks for fixing this.
Jon
