### ISSUE TITLE
HTML-AAM: determine right UIA mapping for browser generated form validation error messages

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#11]
_From @cyns on January 12, 2016 19:37_

_Copied from original issue: w3c/aria#160_

**Comment by jasonkiss** [comment]
Tooltip Control Type?

**Comment by jasonkiss** [comment]
_From @cyns on May 4, 2016 0:11_

Error state mapped 
ControllerFor poining to a Pane with error message
IsDataValidForForm = false

**Comment by boggydigital** [comment]
Cynthia is right, when input is in validation error state property IsDataValidForForm is set to "false" and we create a link to the tooltip element (that is outside DOM) using the ControllerFor. One additional note is that in the current implementation we also map UIA HelpText property to the associated tooltip value and effectively in this case it's mapped to validation error as well. Going forward HelpText might change (e.g. in UIA design it's also supposed to be mapped to the placeholder text), so I'd rather not capture it here - current mapping is the correct one.
