### ISSUE TITLE
do we embrase javascript things?

### ISSUE THREAD

**Issue by asurkov** [w3c/html-aam#111]
Does/should HTML-AAM handle things like javascript:alert()? It feels pretty close to HTML, but still not there. HTML-AAM might be the better match we could have though. @jasonkiss ?

**Comment by jasonkiss** [comment]
It might be reasonable to include some kind of note about it, but I'm not sure where. Otherwise, I feel the same as I do about including CSS mappings: let's keep HTML-AAM focussed on HTML element and attribute mappings. Anyone else have an opinion? @stevefaulkner? @boggydigital?
