### ISSUE TITLE
Complete <ruby> related mappings

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#115]
Need to add entries for `rb` and `rtc`. 

Note that AX has some roles/subroles for `ruby` and associated elements. See [related webkit bug](https://bugs.webkit.org/show_bug.cgi?id=141303).

Not sure if/how these elements are being dealt with in other browsers/APIs.

**Comment by jasonkiss** [comment]
I've added the rows to the mapping table, and completed the AXAPI mappings as best as I can determine. 

Now we need input for MSAA+IA2, UIA, and ATK.

Moving to AAM v2.

**Comment by scottaohara** [comment]
As `rb` and `rtc` are not part of the HTML Living Standard, should they be:
1. removed re: `menuitem` #188 
2. have a comment adding that these elements are not part of the HTML specification

@stevefaulkner ^

**Comment by scottaohara** [comment]
Related discussion about [marking at risk from HTML 5.3](https://github.com/w3c/html/issues/1424).

FWIW, <s>I'm personally leaning more towards adding a comment for now</s>, it seems we should remove them (at least until consensus is reached) as they are outliers in that we don't map other elements/attributes marked as obsolete.
