### ISSUE TITLE
Should header, footer have "Use WAI-ARIA mapping" when scoped to the body element?

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#119]
Currently in the HTML AAM, `header` scoped to the `body` element is mapped to the `banner` role. Similarly, `footer` scoped to the `body` element is mapped to the `contentinfo` role. However, in both cases, they have platform mappings for each platform. So what's the point of the ARIA corresponding role? (rhetorical question)

The macOS and UIA mappings reflect what's in the Core AAM (modulo UIA's Localized Control Type), thus `header` and `footer` when scoped to the `body` element are treated as landmarks. But in ATK and MSAA+IA2, they are given different, non landmark roles. This means that the user experience may vary noticeably depending on platform, which is not ideal.

If `header` and `footer`, when scoped to the `body` element, really should be treated as if the elements had the stated ARIA role, then the MSAA+IA2 and ATK mappings are wrong and should be changed to reflect the mappings in the Core AAM. And if that is indeed the case, then wouldn't it make sense to make the following additional changes:

* For MSAA+IA2, ATK, and macOS replace the current mappings with "Use WAI-ARIA mapping"
* For UIA replace the current mappings with "Use WAI-ARIA mapping, but with Localized Control Type of $TYPE"

**Comment by joanmarie** [comment]
BTW: If you agree with my suggestion, it might also be worth making this change for `aside`:

> For UIA replace the current mappings with "Use WAI-ARIA mapping, but with Localized Control Type of $TYPE"

because it's only the Localized Control Type which differs from the `complementary` role mapping for UIA in the Core AAM.

And perhaps a similar change for `output` for UIA?

**Comment by joanmarie** [comment]
@jasonkiss and @asurkov: What say you? :)

**Comment by jasonkiss** [comment]
I say you are correct, @joanmarie :)

See a1a661d.

I've updated mappings for `header` and `footer` scoped to `body` to use WAI-ARIA mappings, with the exception of UIA's Localized Control Type for both, and AXRoleDescription for `footer`, which is different.

Made similar changes as suggested for `aside` and `output`. 

Thanks!

**Comment by asurkov** [comment]
I agree that the elements having same semantics should be reflected same way in accessibility APIs. However I'm not sure that LANDMARK role is a best fit for headers and footers, that both IA2 and ATK provide the better role match.

@joanmarie do you know why ARIA header and footer equivalents don't use HEADER and FOOTER roles?
