### ISSUE TITLE
Should UIA mappings for text input types say "Use WAI-ARIA mapping"?

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#120]
The `input` types of `email`, `telephone`, and `url` have platform mappings of "Use WAI-ARIA mapping" for all platforms but UIA, in which the `Edit` Control Type is stated, along with a unique Localized Control Type.

The `Edit` Control Type is already specified in the Core AAM's UIA mapping for the `textbox` role. Therefore, should the UIA mappings instead look more like what is done for MSAA + IA2, namely: "Use WAI-ARIA mapping" with the only truly unique-to-HTML addition of the Localized Control Type value?

**Comment by jasonkiss** [comment]
WFM. Done in cdeacad. Thanks @joanmarie for the suggestion.
