### ISSUE TITLE
The sub and sup elements should be mapped for ATK

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#121]
[ATK](https://developer.gnome.org/atk/stable/AtkObject.html#AtkRole) has `ATK_ROLE_SUBSCRIPT` and `ATK_ROLE_SUPERSCRIPT`. These should be used for the `sub` and `sup` elements respectively.

BTW: This mapping was implemented a while ago in WebKitGtk. If it's not implemented in Gecko yet, it should be.

**Comment by jasonkiss** [comment]
Done. Thanks @joanmarie. Closing.
