### ISSUE TITLE
UIA mapping for <span> is incorrect

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aam#124]
The mapping for [span](https://www.w3.org/TR/html-aam-1.0/#details-id-124) currently says:
> UIA  Control Type: Group

When tested using Edge with inspect.exe `span`s are exposed as LocalizedControlType: "text", which seems correct, suggest updating the spec to reflect implementations.

**Comment by jasonkiss** [comment]
Control Type: Text

Done in c6f725e.

Closing.

**Comment by FremyCompany** [comment]
Wait, please do not update UIA mapping without feedback from Microsoft.

**Comment by FremyCompany** [comment]
I cannot reopen, but this is not accurate. @jasonkiss could you please revert?

> `<span tabindex="0">a</span>`
> // outputs a group in the accessibility tree, containing a text node (a)

The `text` nodes you are seeing are the text nodes of the html, the span are not exposed by default since they have no role, so you cannot see them in the tree.

**Comment by boggydigital** [comment]
@FremyCompany is spot on and if I read Steve original post - he's correct as well. The change is not correct.

span elements produce ControlType: Group (as originally specified) and LocalizedControlType: "text" (as Steve correctly noted), which is not the same as ControlType: Text.

I'll add proposed PR to reintroduce ControlType: Group again and capture LocalizedControlType: "text".

**Comment by boggydigital** [comment]
Spoke too soon without double checking - the LocalizedControlType comes from anonymous text block @FremyCompany noted, spans don't get this.

With that - the revert is the only action we need to do here. @jasonkiss

**Comment by jasonkiss** [comment]
Reverted. Thanks @FremyCompany and @boggydigital. Closing again.
