### ISSUE TITLE
IA2 role listed for <footer> inconsistent with implementations

### ISSUE THREAD

**Issue by aleventhal** [w3c/html-aam#133]
The \<footer\> entry recommends following the role used for contentinfo, which has IA2_ROLE_LANDMARK listed. 

However, both Firefox and Chrome, the main IA2 implementers for web, both use IA2_ROLE_FOOTER, which is more specific.  Therfore there is an inconsistency between current implementations and the spec.

Options:
- Ask Firefox and Chrome to use IA2_ROLE_LANDMARK for consistency with the spec, and consistency with all other landmarks, since it appears all the other landmarks do actually use IA2_ROLE_LANDMARK.
- Change the spec so that IA2 implementations should always use the more specific role when available. In this case we should be specing/implementing IA2_ROLE_COMPLEMENTARY_CONTENT for complementary, which we currently do not.

**Comment by asurkov** [comment]
I'd say we should use the better match from what API provides. If no objections, I can file a patch.

**Comment by aleventhal** [comment]
Surkov, so we should use IA2_ROLE_FOOTER for this one?

**Comment by asurkov** [comment]
@aleventhal I would say so.

**Comment by aleventhal** [comment]
@asurkov sounds good to me

**Comment by asurkov** [comment]
@aleventhal check out issue #119, where footer/header roles were converted to landmarks

**Comment by aleventhal** [comment]
@asurkov I don't care what we do for these. I think JAWS/NVDA handle it either way. They're probably just looking at xml-roles. But, I'd like to do it the same as Firefox and the official mappings. What's the final decision?

**Comment by asurkov** [comment]
@aleventhal #119 seems has a valid point, because the semantics of ARIA banner/contentinfo roles and HTML header/footer elements looks same. Thus I filed an issue against core-aam (https://github.com/w3c/core-aam/issues/19) to make them using more specific IA2 roles.

**Comment by jongund** [comment]
Some times the FOOTER and HEADER elements do represent a landmark and some times they don't, so the mapping should be conditional based on the content of the FOOTER and HEADER element.

**Comment by asurkov** [comment]
@jongund sure, I meant the case when HTML header/footer are semantically equivalent to banner/contentinfo.

**Comment by carmacleod** [comment]
@aleventhal @asurkov 

I think https://github.com/w3c/core-aam/issues/19 should be closed (see https://github.com/w3c/core-aam/issues/19#issuecomment-771160817).

So I think we should go with Option 1 in the opening comment of this issue:
> Ask Firefox and Chrome to use IA2_ROLE_LANDMARK for consistency with the spec, and consistency with all other landmarks, since it appears all the other landmarks do actually use IA2_ROLE_LANDMARK.
