### ISSUE TITLE
Add mappings for ins and del

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#141]
The `ins` and `del` elements currently are shown as having no accessible object for three of the four platforms. In addition, for ATK it states that exposure should be done via text attribute.

In order to easily support presentation (or exclusion, should the user prefer) of edits marked up via `ins` and `del`, I think there should be an accessible object. IAccessible2 has just added roles for each of these: https://github.com/LinuxA11y/IAccessible2/blob/master/api/AccessibleRole.idl#L307. ATK and AT-SPI2 will soon, hopefully: https://gitlab.gnome.org/GNOME/atk/issues/2.

In terms of the mappings for ATK, until the new roles have been created, I think using ROLE_SECTION makes sense (i.e. the same mapping as `div` because `ins` and `del` can have child elements.) 

We still need a way to make it easy for ATs in Linux to find these elements. A text attribute (be it formatting or something like `diff:del`/`diff:ins`) doesn't make sense to me as Orca doesn't bother getting text attributes unless a user explicitly asks for them via command. Checking all text attributes on the slim chance there's an `ins` or `del` will not be performant. Orca does, for a variety of reasons, check object attributes. Thus I think exposure via object attribute is the way to go. Could we use `xml-roles` for that? If not, an object attribute like `diff:del` and `diff:ins` should work.

**Comment by joanmarie** [comment]
@melanierichards: This IA2 now exposes these via IA2_ROLE_CONTENT_INSERTION and IA2_ROLE_CONTENT_DELETION. And we'll be exposing them for ATK as well. What about for UIA?

**Comment by scottaohara** [comment]
@melanierichards @stevefaulkner I've started [a branch for updating `del` and `ins`](https://github.com/w3c/html-aam/tree/141_ins_del), please feel free to update if you have time.

Thoughts I was having: do we want to add a comment to each referencing that [`role=insertion`](https://w3c.github.io/aria/#insertion) and [`role=deletion`](https://w3c.github.io/aria/#deletion) are in draft?
