### ISSUE TITLE
Should var really be mapped to "No accessible object"?

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#143]
It appears to me that `var` has semantic meaning rather than being purely stylistic. As such, I'm not sure that "no accessible object" is the correct mapping for MSAA+IA2, UIA, or ATK. For that matter, I wonder if making it an AXGroup with no means to distinguish it from other generic AXGroup instances is what is desired for macOS.

One use case that springs to my mind would be variables which consist of more than one letter. Should <var>ab</var> be pronounced as "a b" or the first syllable in abdomen? If the latter, well, perhaps never mind. But if it's the former, how is a screen reader to know it should "spell" out the variable name if all it's told is the font happens to be italics?

**Comment by joanmarie** [comment]
Assuming it should have an accessible object, for ATK I guess ATK_ROLE_STATIC would be the best match. ATs would still need a means to know that this particular ATK_ROLE_STATIC object is a `var`. Could that be done via the `xml-roles` object attribute?

**Comment by scottaohara** [comment]
i personally think this should be done by xml roles, and / or a corresponding general "code" role for AIRA.

hoping to submit a proposal for that next week to the ARIA spec per [issue 527](https://github.com/w3c/aria/issues/527), but would be happy to discuss this further.

**Comment by scottaohara** [comment]
closing this issue as `var`will be mapped to "generic" once the 'inline' version of that role is specified in core aam
