### ISSUE TITLE
Details and Summary mappings should include details/details-for AtkRelationType

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#147]
ATK has the following relation types:

> ATK_RELATION_DETAILS
> Reciprocal of ATK_RELATION_DETAILS_FOR. Indicates that this object has a detailed or extended description, the contents of which can be found in the target object(s). This relation type is most appropriate for information that is sufficiently lengthy as to make navigation to the container of that information desirable. For less verbose information suitable for announcement only, see ATK_RELATION_DESCRIBED_BY. If the detailed information describes an error condition, ATK_RELATION_ERROR_FOR should be used instead. Since : ATK-2.26.
> 
> ATK_RELATION_DETAILS_FOR
> Reciprocal of ATK_RELATION_DETAILS. Indicates that this object provides a detailed or extended description about the target object(s). See also ATK_RELATION_DESCRIPTION_FOR and ATK_RELATION_ERROR_FOR. Since : ATK-2.26.

These should be included in the implementations of the `details` and `summary` elements so that Orca can quickly figure out what information should be presented upon expansion of the element.

**Comment by scottaohara** [comment]
ping @stevefaulkner 

let's look at this next week per our discussion today.

**Comment by scottaohara** [comment]
@joanmarie, i'm going to include this work with my PR #224 and will let you know as soon as I get that done for review.

sound good?

**Comment by joanmarie** [comment]
Yup! Thanks @scottaohara.
