### ISSUE TITLE
HTML-AAM: UIA mapping for <tr>

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#15]
_From @cyns on January 12, 2016 23:13_

Generally not mapped. If the element must be included per Core-AAM Section 5.1.2, map as <code>Group</code>.

_Copied from original issue: w3c/aria#180_

**Comment by jasonkiss** [comment]
_From @cyns on February 25, 2016 4:26_

Need to add respec link to CORE-AAM

**Comment by jasonkiss** [comment]
So it's not going to be normally mapped as role=row? Okay if not, but then wouldn't it be mapped as role=row (as DataItem ControlType) when it is included in the a11y tree?

**Comment by jasonkiss** [comment]
@boggydigital Is the current UIA mapping for `tr` still accurate?

**Comment by boggydigital** [comment]
The current mapping is accurate. Can be improved in the light of #58, but there is nothing wrong with the current mapping, so I'll just close the issue. I don't see <tr> being mapped through role="row" currently and they are indeed exposed as ControlType: Group element.
