### ISSUE TITLE
Section 5.3.1 (input type="image") as written can lead to non-interoperable implementations

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#150]
I'm seeing inconsistent implementations of the accessible name for `input type="image"` with a title attribute. More specifically, WebKit and Gecko expose the value of the `title` attribute; Blink exposes "Submit". Looking at how section 5.3.1 is written, I would argue both are correct due to item 4 in the current spec text:

> 5.3.1 input type="image" Accessible Name Computation
> 1. If the control has an aria-label or an aria-labelledby attribute the accessible name is to be calculated using the algorithm defined in Accessible Name and Description: Computation and API Mappings 1.1.
> 2. Otherwise use alt attribute
> 3. Otherwise use value attribute
> 4. Otherwise the user agent may provide an accessible name via a localized string of the phrase "Submit Query"
> 5. Otherwise use title attribute
> 6. If none of the above yield a usable text string there is no accessible name

This seems bad for interoperability.

Note: At the present time, the ARIA Working Group has a test case for the scenario. I was going to provide a patch to fix the issue in Blink, but technically they don't seem to have a bug.

**Comment by stevefaulkner** [comment]
Hi @joanmarie how would you change the above? Note that I wrote most of the these an age ago (6 years hmmm), pretty much based on what i found was implemented at the time

**Comment by joanmarie** [comment]
If you swap the order of 4 and 5, the Blink would have a bug because they are not using the title.

**Comment by stevefaulkner** [comment]
test case 05: https://thepaciellogroup.github.io/AT-browser-tests/test-files/input-image.html

**Comment by joanmarie** [comment]
Suh-weet! :) Got my fix here: https://chromium-review.googlesource.com/c/chromium/src/+/1246724

Thanks much @stevefaulkner!!
