### ISSUE TITLE
Need language/mapping for "not-mapped" elements which must be exposed due to attributes

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#151]
Consider the following:
    `<b tabindex="0">foo</b>`
Because it is focusable, it has to have an accessible object (i.e. be mapped) so that accessibility events can be emitted.

Likewise: `<b title="hello world!">foo</b>` would need an accessible object because otherwise there's no way to expose and associate the title value.

At the present time, the HTML-AAM lacks language/mapping for a number of inline elements. There should be either language (a normative note) or mappings for how to expose "not mapped" elements which must be exposed due to attributes.

As for what the mappings should be, a quick glance makes me think that the content for "a (no href attribute)" is the expected result for all platforms for the sorts of things I've described.

**Comment by scottaohara** [comment]
Discussed this a bit today.  @stevefaulkner and I will spend more time on this next week.

Thanks!

**Comment by stevefaulkner** [comment]
[test case](https://codepen.io/stevef/pen/gBMJKq) to look at what happens currently

**Comment by joanmarie** [comment]
ping?

**Comment by stevefaulkner** [comment]
@joanmarie bit aggressive, only been 6 months ;-)

I think that yes an indication that an element is focusable but not actionable needs some role/state description that can be provided to the user, so they know what the hell the thing is. I am unsure what the appropriate description for it would be though.

**Comment by scottaohara** [comment]
Would this then also necessitate a check for an event tied to the element?  

e.g.
`<b tabindex="0">foo</b>` exposed as... whatever it gets exposed as.

but
`<b tabindex="0">foo</b>` where there's a JavaScript event associated with the element, thus making it actionable, would necessitate an alternate role/state?

**Comment by joanmarie** [comment]
I was thinking of something simpler than what is being described here.

If you look at https://w3c.github.io/html-aam/#el-span, for ATK it says:
> Not mapped

That is incorrect. If (for whatever reason) it needs to be mapped, the correct mapping would be `ATK_ROLE_STATIC`.

So why not replace "Not mapped" with  something like:
> If mapped, `ATK_ROLE_STATIC`

or:

> `ATK_ROLE_STATIC` (if mapped)

Personally, I think that would be enough. And this would need to be done for all `span`esque elements.

**Comment by scottaohara** [comment]
Thanks for clarifying @joanmarie 

Spoke with @stevefaulkner and I'll start working on a PR for this asap.

**Comment by carmacleod** [comment]
Would need to add "if mapped" for all `div`esque elements as well (including removing the "May not have accessible object" preamble).

Please see @joanmarie's https://github.com/w3c/html-aam/issues/191#issuecomment-502818575 for a short definition of "if mapped" that can be added as a new bullet to the [HTML AAM Element Role Mappings](https://w3c.github.io/html-aam/#html-element-role-mappings) Notes (right after the bullet about "Not mapped").

**Edit:** I've closed #191, so for convenience, here are @joanmarie's words for the new bullet:
- "If mapped" means the element is conditionally exposed in the accessibility tree. User agents MUST map the element if it is interactive or has semantic meaning. User agents MAY also include this element in the accessibility tree for implementation-specific reasons.

**Comment by scottaohara** [comment]
This issue has been largely resolved by the decision to make a good majority of the elements that would have been described this way map to `generic`.

both feel really silly that this has been open for over 3 years... and also glad to not have to undo a bunch of work with how decisions about `generic` shaped up...

There are a few elements left that could still benefit from this as we determine if they need specific roles, or if they would then eventually map to generic as well.

This might be useful to incorporate with the "not mapped" definition in general... as there will still be some elements that don't map... but if someone were to take, a style element for example, and make that display block / tabindexed.... then that should likely be treated as `generic` as well.
