### ISSUE TITLE
Should this repo use aria-common css and js

### ISSUE THREAD

**Issue by nschonni** [w3c/html-aam#155]
Seems like there is some overlap with the img, css, scripts.
Adding the repo name to https://github.com/w3c/aria-common/blob/5b936832c880dda63358a5374b0fc3dca4cb676a/.travis.yml#L14 should create a "common" folder in here. Then the `index.html` paths would need to be updated.

**Comment by scottaohara** [comment]
closing this per the maintenance work being done to get this repo aligned with other WebApp WG specs.

Thanks!
