### ISSUE TITLE
Update mappings for address element

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#170]
This issue is to track the removal of the `address`'s unique properties to expose "address" to the different platform's accessibility APIs. These do not appear to have been presently implemented, nor seem to be necessary.

Instead, while `address` may be used as a semantic HTML element, it should not provide any special roles or announcements beyond that of a `div`, as the content of the element itself should be sufficient to indicate its purpose (an address / contact information).

Per ARIA's [#872: Create address role](https://github.com/w3c/aria/issues/872), discussing with @stevefaulkner, doing some quick screen reader testing with the `address` element, and [tweets](https://twitter.com/stevefaulkner/status/1100370102879440897).

To further keep track of issues / decisions per the mapping history of `address`, here are related issues:
* [#166: Verify the IA2 mappings for the address element](https://github.com/w3c/html-aam/issues/166)
* [#164: The address element should map to ATK_ROLE_SECTION; not ATK_ROLE_PANEL](https://github.com/w3c/html-aam/issues/164)
* [#33: should address be treated as section/landmark in AAPIs?](https://github.com/w3c/html-aam/issues/33), relates to #32. 

Additionally, a [Webkit issue filed - "AX: Reconsider role for "address" tag"](https://bugs.webkit.org/show_bug.cgi?id=194654).

**Comment by joanmarie** [comment]
Related: I fixed this in Chrome/Chromium a couple of weeks ago: https://chromium-review.googlesource.com/c/chromium/src/+/1448739
