### ISSUE TITLE
Update mappings for sub and sup for IA2

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#174]
After some discussion in a Mozilla issue, the [conclusion](https://bugzilla.mozilla.org/show_bug.cgi?id=1175640#c8) is that `sub` and `sup` should have accessible objects in addition to exposing the properties via text attribute. The mapping should be to `IA2_ROLE_TEXT_FRAME`.

Will do a pull request shortly.

**Comment by joanmarie** [comment]
So I have a "draft" pull request (#175). It's a draft because, as I've since [commented on the Mozilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1175640#c9), it's not clear to me if "keep(ing) the text attributes as they are" means on the parent container or the text frame which is now being exposed (or both). Once Jamie chimes in, I'll finalize my PR.

**Comment by scottaohara** [comment]
Thank you

**Comment by joanmarie** [comment]
My pleasure. Jamie has answered on the bug and I've updated my pull request accordingly. Please review. Thanks!

**Comment by scottaohara** [comment]
closed by #175
