### ISSUE TITLE
Clarify mapping for hidden attribute

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#178]
Per the issue [hidden attribute not mapped to aria-hidden](https://github.com/WhatSock/w3c-alternative-text-computation/issues/16), we should make it clear that `hidden` maps to `aria-hidden=true` but, if the display of the hidden element is modified (e.g. display block, inline-block, etc) then `hidden` should no longer be considered mapped to `aria-hidden=true`.

Per the HTML spec:
> Because this attribute is typically implemented using CSS, it's also possible to override it using CSS. For instance, a rule that applies 'display: block' to all elements will cancel the effects of the hidden attribute. Authors therefore have to take care when writing their style sheets to make sure that the attribute is still styled as expected.

**Comment by xi** [comment]
I would frame it differently: `hidden` does in fact not map to anything regarding `aria-hidden`. But it does imply `display: none` which in turn maps to `aria-hidden="true"`. So the mapping is only indirect (if this interpretation is correct).

**Comment by stevefaulkner** [comment]
so mapping is 
`hidden=display:none` = `aria-hidden=true`
`hidden=display:anything else` = not mapped

**Comment by xi** [comment]
I honestly feel like the fix adds more to the confusion that it helps. Why not simply remove the mapping for `hidden`? `display: none` is already mapped, so this is not necessary.

**Comment by scottaohara** [comment]
But it doesn't not map, so saying it doesn't map wouldn't be correct.

Per your comment in the original thread:
>This implementation seems to rely on the fact that `hidden` also visually hides the element.

The native `hidden` implementation does visually hide the element, but the element not being revealed to the accessibility tree is what shares the mapping with `aria-hidden=true`.  It just so happens it's natively done via `display: none`.

Additionally your comment:
>`hidden` implies `display: none` which in turn implies `aria-hidden="true"`. But if an author manually sets display: block, `hidden` should still imply `aria-hidden="true"`

Is exactly why this clarification was made, because modifying the CSS of the `hidden` attribute to not be the default `display: none` is what will sever the mapping, as long as alternate CSS to continue to hide the element from the a11y tree is not used instead.

Additionally, the fact the attribute continues to exist in the DOM doesn't mean it continues to map to `aria-hidden="true"` when the mapping has been severed.  

As a parallel, `<input type="checkbox" checked>` being set in the DOM means that unless altered, the checkbox will be checked, which would map to `aria-checked="true"`.  

However, if a user has unchecked the checkbox, `checked` doesn't get removed from the DOM.  But the checkbox has been modified to be in the unchecked state, so it communicates itself as unchecked to the accessibility tree.  Same logic applies to `hidden`.  Just because the attribute is there, if it's CSS has been modified to sever the mapping to `aria-hidden=true`, then it no longer maps.

**Comment by xi** [comment]
But `display: none` also hides the element from the accessibility, doesn't it?

https://www.w3.org/TR/wai-aria-1.2/#aria-hidden

**Comment by scottaohara** [comment]
Yes.

**Comment by xi** [comment]
My point is: This whole "it does map to `aria-hidden`, but only if `display` is not set" is kinda complicated and potentially confusing. Just *not mentioning* `hidden` is IMHO much easier to understand.

The [HTML spec](https://www.w3.org/TR/html51/editing.html#the-hidden-attribute) clealy describes the effect of `hidden` on `display`. The [ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#aria-hidden) clearly describes the effect of `display` on `aria-hidden`. Duplicating this here just adds confusion.

To be precise: As far as I understand, `hidden` does not map to `aria-hidden`. It only has an indirect effect via `display`. Or am I getting this wrong?

**Comment by scottaohara** [comment]
The default behavior of the `hidden` attribute matches the affect that `aria-hidden="true"` has on the accessibility API. This is why they map. 

If the `hidden` attribute is modified by CSS to undo its default behavior, then it no longer matches how elements marked as `aria-hidden="true"` are communicated to the accessibility API. Thus in these situations it no longer maps to `aria-hidden="true"`. 

The `hidden` attribute is part of the HTML specification, and HTML AAM is meant to indicate how HTML maps to accessibility APIs. This is why `hidden` is documented here, and why it will not be removed.
