### ISSUE TITLE
Instances of Web Platform WG text

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#185]
There are instances in the spec where we mention "Web Platform Working Group" and "Web Platform WG".

@marcoscaceres should I update these to Web Applications Working Group?  Or keep a reference to the change in some places while updating in others?

Thanks

**Comment by marcoscaceres** [comment]
That would be great, thanks!

**Comment by scottaohara** [comment]
But which of the two options, @marcoscaceres ?  ;)

**Comment by marcoscaceres** [comment]
Heh, sorry! Just update the references as they make sense.

**Comment by scottaohara** [comment]
sounds good.  thanks :)
