### ISSUE TITLE
Add HTML elements

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#189]
The following elements are in the HTML Living Standard but are not represented here.

- [ ] [hgroup](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element)
- [ ] [slot](https://html.spec.whatwg.org/multipage/sections.html#the-slot-element)
- [ ] [autonomous custom element](https://html.spec.whatwg.org/multipage/custom-elements.html#autonomous-custom-element)

**Comment by scottaohara** [comment]
This issue will be picked up once #226 is completed.

**Comment by scottaohara** [comment]
copied from ARIA in HTML issue regarding custom elements:
Per: HTML issue 4658 and ARIA issue 984, it should be specified that a custom element may have no corresponding role (map to generic) or may have a role set by `ElementInternals`. 

If the role is set in that way, and the custom element doesn't merely act as a container for child elements (light or shadow dom) with their own roles, then the listing for the custom element would need to indicate that it either maps to generic, OR the role set by `ElementInternals`, and to reference THOSE roles for appropriate mappings.

**Comment by carmacleod** [comment]
Can we create a separate issue for `hgroup` so that it is not held up waiting for autonomous custom elements? Is hgroup "Not mapped" everywhere? Does it need to wait for the "If mapped" PR #226?

(For context, I'm hoping to point to `hgroup` (and `slot`) from the html spec, but at present, they're missing from html-aam). :)

**Comment by scottaohara** [comment]
I do not think #226 should be a blocker here anymore, per my comment today in that issue's WIP PR.

`hgroup` is not mapped anywhere and may well continue to be unmapped (though impact the heading levels of contained elements) depending on how that gets reworked in the HTML spec.

`slot` is not mapped, nor should it be.

autonomous custom elements are either `role=generic` or mapped to the role declared via its `ElementInternals`.

form associated custom elements should map to the form-related role declared via its `ElementInternals`.
