### ISSUE TITLE
a element exposed as link regardless of whether a href is present

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aam#196]
in firefox/chrome on windows(other browsers not checked yet) the `<a>` element without a `href` still has a `role=link`.
@joanmarie is this the case in linux browsers
@scottaohara what about Mac?
[test file](https://thepaciellogroup.github.io/AT-browser-tests/test-files/a-no-href.html)

**Comment by scottaohara** [comment]
@stevefaulkner reports as AXStaticText when checking Safari

checking chrome's computed properties panel, it has a role of "Anchor" where an `a href` has a role of "Link"

**Comment by scottaohara** [comment]
related Android Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1566878
