### ISSUE TITLE
"Other form elements" doesn't say to use all associated label elements

### ISSUE THREAD

**Issue by zcorpan** [w3c/html-aam#209]
> 5.7.1 Other Form Elements Accessible Name Computation
> 1. If the control has an aria-label or an aria-labelledby attribute the accessible name is to be calculated using the algorithm defined in Accessible Name and Description: Computation and API Mappings 1.1.
> 2. Otherwise use label element.

The earlier section on `input` says

> Otherwise use the associated label element(s) accessible name(s) - if more than one label is associated; concatenate by DOM order, delimited by spaces.

This wording should be used for "other form elements" as well.

**Comment by zcorpan** [comment]
cc @spectranaut

**Comment by scottaohara** [comment]
closing this issue.  we have  #210 and not all the form elements that essentially fall under this category can be named / named by a label element.

will work on getting this resolved.
