### ISSUE TITLE
<summary> - should "Details" be localized?

### ISSUE THREAD

**Issue by zcorpan** [w3c/html-aam#212]
https://w3c.github.io/html-aam/#summary-element-accessible-name-computation

This doesn't say to localize "Details", unlike other places in the spec.

**Comment by scottaohara** [comment]
Good point.  This text should also be update to clarify that the fallback string from the UA only appears if the `details` is lacking a `summary` all together.  As an empty `<summary></summary>` does not produce "details"

**Comment by zcorpan** [comment]
cc @spectranaut
