### ISSUE TITLE
ATK mappings for ins and del need to be updated

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#218]
https://github.com/w3c/html-aam/issues/141 added mappings for ATK, however there are a couple of issues:

1. There is no attribute included to identify that the ATK_ROLE_SECTION is an insertion or deletion. In order to be consistent with what has been done for other elements which have corresponding ARIA roles, I propose adding `xml-roles:insertion` for `ins` and `xml-roles:deletion` for `del`. This will be going into the Core-AAM.
2. As agreed upon earlier, we should wait for the platform new roles to land in ATK and AT-SPI2. That has happened. See https://gitlab.gnome.org/GNOME/atk/commit/e3856ee2. The Core-AAM will also contain the new roles (ATK_ROLE_CONTENT_INSERTION and ATK_ROLE_CONTENT_DELETION)

I'm happy to do a pull request, but I don't know how you feel about when it's best to do 2.

**Comment by joanmarie** [comment]
Went ahead and did the pull request just in case. If you disagree, we can close it.

**Comment by scottaohara** [comment]
Hey @joanmarie. 2 prs are fine with me. The second can be noted as not ready for merge until the time is right.
