### ISSUE TITLE
What does "Use WAI-ARIA mapping" actually mean?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/html-aam#221]
If you navigate to, for example:
https://w3c.github.io/html-aam/#el-output

In the second column it says "Use WAI-ARIA mapping", but that doesn't link to anything? I was hoping to land there and get some more clear instructions on how to implement stuff. If anything, "Use WAI-ARIA mapping" should be linked to the right place (to WAI-ARIA? dunno?).

**Comment by LJWatson** [comment]
It's a reference to the [Core AAM](https://www.w3.org/TR/core-aam-1.1/) 
mapping for that element or attribute. It might be worth making those 
references links perhaps?

**Comment by scottaohara** [comment]
The row column notes:
Accessible Rich Internet Applications (WAI-ARIA) 1.0 / status role (which is a link to core aam)

the other rows/columns are referencing the "status role" link.  in this particular example, there may still be additional information that is available beyond the matching of the core aam mapping, e.g. UIA's  `Localized Control Type: "output"`

**Comment by scottaohara** [comment]
Let's move any further conversation of this to #122 as this is a related topic to that one.
