### ISSUE TITLE
footer and header should be output as contentinfo and banner independent of the ancestor elements

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#222]
In my opinion the distinction between "scoped to the body element" and "scoped to the main element, a sectioning content element, or a sectioning root element other than body" at the footer and header should be abolished.

Reasons:
1. The distinction is not made for the corresponding ARIA roles (https://www.w3.org/TR/core-aam-1.1/: banner, contentinfo).
2. The distinction is not uniformly specified (see, for example, https://www.w3.org/TR/wai-aria-practices/examples/landmarks/banner.html: "The HTML5 header element is not considered a banner landmark when it is descendant of any of following elements: article, aside, main, nav, section"; https://www.w3.org/WAI/tutorials/page-structure/regions/: "If the <header> element is used inside article and section elements, it is not associated with the whole page, but only with that specific article or section"; https://w3c.github.io/html-aam/: "scoped to the main element, a sectioning content element (article, aside, nav, section), or a sectioning root element (blockquote, details, dialog, fieldset, figure, td) other than body"; https://html.spec.whatwg.org/multipage/dom.html#sectioning-content: "Sectioning content is content that defines the scope of headings and footers"; https://html.spec.whatwg.org/multipage/sections.html#the-footer-element: "The footer element represents a footer for its nearest ancestor sectioning content or sectioning root element ... When the nearest ancestor sectioning content or sectioning root element is the body element, then it applies to the whole page"; https://www.w3.org/TR/html52/single-page.html#elementdef-header: "The header element represents introductory content for its nearest ancestor main element or sectioning content or sectioning root element.")
3. The distinction leads to incorrect output by the screenreader (https://github.com/FreedomScientific/VFO-standards-support/issues/216).
4. The distinction is not useful for web developers and makes no sense from a accessibility point of view.

If necessary, the ARIA specification should also be adapted (https://www.w3.org/TR/wai-aria-1.1/#banner: "Within any document or application, the author SHOULD mark no more than one element with the banner role.")

**Comment by scottaohara** [comment]
Thanks for opening the issue.  

I will comment on / clarify each of your points:

1. The Core AAM indicates how the roles themselves are mapped.  HTML AAM indicates how the HTML elements should map or what roles they should map to as defined in Core AAM. Furthermore, this specification indicates the conditions that may allow (or not) for such mappings.  This is why there is no distinction made in Core AAM.
2. While the wording for when a `header` or `footer` should be exposed as a `banner` or `contentinfo` is not exactly the same between each of the linked resources, no resource contradicts the other.
3. Bugs/gaps with assistive technology or browsers should be corrected. This specification (nor any other) should be changed to accommodate bugs, as that would then cause breaking changes for all the instances of where these elements were used correctly, as presently defined.
4. As you've stated this is your opinion, so there's no clarification needed for this point.

Beyond potentially clearer authoring guidance to indicate a single `banner` or `contentinfo` landmark, per document, should typically be exposed to assistive technologies, pending special circumstances, and that assistive technologies & browsers should fix gaps in adhering to the specification, there should be no change to *this* specification.

**Comment by JAWS-test** [comment]
@scottaohara 

Thanks for the answer. Unfortunately, I disagree on some points.

1. Is clear
2. The sources contradict each other because they specify different conditions when footer and header are to be recognized as landmark regions. That causes confusion. The problem here is that the sources primarily used by developers (namely the HTML specification) do not impose any restrictions on the output. This partly also applies to the W3C specification: https://www.w3.org/TR/html52/sections.html#the-footer-element ("Allowed ARIA role attribute values: contentinfo role (default - do not set)"). 
The HTML AAM document will not be used by developers as a primary source.
3. Is clear
4. See point 2

Furthermore, the question would be why the output of footer and header is limited. Both elements have no effect on the visual design of the page, but serve to structure the page, which primarily benefits users of assistive technology (such as screen readers). This means that a web developer uses the landmark regions to convey the visual page structure to blind users, for example. The HTML specification allows header and footer in many places in the source code, but only in a few places should it be output. What is the purpose of this rule? 
Other landmark regions can also be used several times, the specification only says that they have to be labeled. The page structure does not become confusing if all footers and headers are displayed, because e.g. JAWS correctly displays the nesting of the landmark regions in the element overview.

I therefore suggest that HTML AAM be adapted with regard to header and footer. If this is not possible, at least the other W3C documents should be standardized so that the information is not contradictory. In addition, the question would be whether the HTML specification, which unfortunately is no longer maintained by the W3C, can be adapted.

**Comment by scottaohara** [comment]
Your reference in point 2 doesn't prove the point you seem to think it does.  HTML 5.2 is restating content from ARIA in HTML.  Following the link of "do not set" from the "Allowed ARIA role attribute values" portion notes the following:
>In the majority of cases setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and not recommended as these properties are already set by the browser.  

>Authors are encouraged to make use of the following documents for guidance on using ARIA in HTML beyond that which is provided in this section:  

> Using ARIA - A practical guide for developers on how to add accessibility information to HTML elements using the Accessible Rich Internet Applications specification [wai-aria-1.1].
> WAI-ARIA Authoring Practices 1.1 - An author’s guide to understanding and implementing Accessible Rich Internet Applications.


That said, the point of the 5.2 reference was that there should be no reason to set `role=contentinfo` to a `footer` element, because under the proper conditions / correct browser implementation, it will be conveyed as such. Those conditions are noted in this specification, and via different wording in HTML 5.2:
>When a footer element’s nearest ancestor sectioning root element is the body element, and it is not a descendant of the main element or a sectioning content element, then that footer is scoped to the body element and represents a footer for the page as a whole.  

>Assistive Technology may convey to users the semantics of the footer element when it applies to the whole page. This information can provide a hint as to the type of content. For example, the role of the element, which in this case is "content information", can be announced by screen reader software when a user navigates to a footer element that is scoped to the body element.

HTML 5.2 was explicit with this information compared to The HTML Living Standard:
>When the nearest ancestor sectioning content or sectioning root element is the body element, then it applies to the whole page.

But the fundamental information remains the same in that when a footer applies to the document itself, it should be treated differently.

Looking over to [ARIA, it states](https://www.w3.org/TR/wai-aria-1.1/#contentinfo):
>A large perceivable region that contains information about the parent document.  Examples of information included in this region of the page are copyrights and links to privacy statements. ... Within any document or application, the author SHOULD mark no more than one element with the contentinfo role.

Further outlined for authors in [ARIA Practices 1.1](http://w3c.github.io/aria-practices/#aria_lh_contentinfo) (as well as the older version you linked to) states:
>The HTML footer element defines a contentinfo landmark when its context is the body element.
The HTML footer element is not considered a contentinfo landmark when it is descendant of any of following elements (see HTML Accessibility Mappings [HTML-AAM]): 

So again, the information is not contradictory. If anything it all builds off from each other.

**Comment by JAWS-test** [comment]
I wrote "partly" because it is still explained in HTML 5.2 (even if "may" instead of "should" or "must" leaves something open: "Assistive Technology may convey to users the semantics..."). But the problem is that HTML 5.2 is no longer valid, but the Living Standard, there is no longer any indication that header and footer should be ignored by assistive technology in most use cases.

The next problem is that, according to the ARIA specification, one header and footer is allowed for each document and application role, and therefore several headers and footers per page: "Within any document or application, the author SHOULD mark no more than one element with the contentinfo role". Permitted would be for example
```
<div role=application>
	<div role=contentinfo></div>
	<div role=document>
		<div role=contentinfo></div>
	</div>
</div>
```
but also 
```
<div role=document>
	<div role=contentinfo></div>
</div>
<div role=document>
	<div role=contentinfo></div>
</div>
```
So this is not consistent to the HTML elements header and footer.

On the page https://www.w3.org/WAI/tutorials/page-structure/regions/ there are no hints for the restricted use of header and footer. It is only said that within article and section the header and footer refer to the area: "Note: If the footer element is used inside article and section elements, it is not identified as the footer for the whole page but only relates to that specific article or section". This page seems to be outdated and should therefore be deleted or marked as outdated.

On the page https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html and analog on the page http://w3c.github.io/aria-practices/#aria_lh_contentinfo: "footer = contentinfo when in context of the body element. The footer element is not a contentinfo landmark when it is a descendant of the following HTML5 sectioning elements: article, aside, main, nav, section". This pages describe the use of header and footer better, but still not correctly. There definition also contains fewer elements that suppress the output of header and footer than the definition in HTML AAM: blockquote, details, dialog, fieldset, figure, td (https://html.spec.whatwg.org/multipage/sections.html#sectioning-root).

**Comment by scottaohara** [comment]
This is becoming a circular argument which is not productive.

So putting discrepancies you may perceive with the various specifications aside, your issue can be best summed up with your introductory sentence:
>In my opinion the distinction between "scoped to the body element" and "scoped to the main element, a sectioning content element, or a sectioning root element other than body" at the footer and header should be abolished.

You listed your reasoning, but no feasible solution that wouldn't either result in a complete unmapping of `header` and `footer` elements to any meaningful semantics, or produce an over abundance of landmarks being exposed in the browser and screen reader pairings that have  gotten the implementation correct.

While we agree there are bugs in implementation, the problem with this exists there and not with the manner in which HTML AAM indicates these elements should be mapped.

**Comment by JAWS-test** [comment]
I consider the complete output of all headers and footers by assistive technology to be useful. There are also pages with more than 100 headings and one could argue that this would be too much to efficiently recognize the structure of a page with the screenreader. But fortunately, there are headline hierarchies that make this possible. In the same way, the purpose of correctly nested header and footer is efficiently to capture, since the hierarchy can also be output (and is also output by JAWS).

I think it's wrong if semantics used correctly according to the HTML specification for structuring pages are not output to blind users, although exactly this marking is primarily intended for blind users.

**Comment by LJWatson** [comment]
Whilst noting that this issue is closed, it's worth being clear that ARIA and HTML are not the same thing. What is permitted in one does not have to be permitted in the other, although neither should conflict.
