### ISSUE TITLE
Review mappings once new roles are added

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#229]
ARIA 1.2 will introduce various new roles and mappings for greater parity with HTML.

After publication, we should review the HTML AAM's element mappings and ensure that any necessary elements are mapped to their appropriate WAI ARIA roles.

For instance, `del`, `ins`, `meter`, `dl`, `dt`, `dd`, `strong`, `em`, among others and many that will map to ARIA's `role=generic` but would also likely benefit from continued exposure of API specific information.

EDIT:

list of mappings to track in this issue.  `generic` will be handled separately
- [x] `blockquote` => `<blockquote>`
- [ ] `caption` => `<caption>` and `<figcaption>`
- [x] `code` => `<code>`
- [x] `deletion` => `<del>`
- [x] `emphasis` => `<em>`
- [x] `insertion` => `<ins>`
- [x] `meter` => `<meter>`
- [x] `paragraph` => `<p>`
- [x] `strong` => `<strong>`
- [x] `subscript` => `<sub>`
- [x] `superscript` => `<sup>`
- [x] `time` => `<time>`

**Comment by scottaohara** [comment]
note `generic` in Core AAM Editor's draft: https://github.com/w3c/core-aam/commit/3d7477ddd3e610801987eef6221c3ce246c6773f

**Comment by joanmarie** [comment]
> note generic in Core AAM Editor's draft: w3c/core-aam@3d7477d

Related: It looks `div`esque rather than `div`+`span`esque because we haven't yet landed text separation. Treating generic as a `div` means we can proceed with implementation.

**Comment by scottaohara** [comment]
notes for future updating:
* `sub` to [`subscript`](https://w3c.github.io/core-aam/#details-id-73)
* `sup` to [`superscript`](https://w3c.github.io/core-aam/#details-id-74)
* `time` to [`time`](https://w3c.github.io/core-aam/#details-id-83)
* `meter` to [`meter`](https://w3c.github.io/core-aam/#details-id-48)

**Comment by MarcoZehe** [comment]
Note: Also map the `<code>` element to what ARIA 1.2 proposes. Especially the ATK and IA2 mappings differ.

**Comment by stevefaulkner** [comment]
@scottaohara `dl` will map to generic?
