### ISSUE TITLE
combobox for select is wrong

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#230]
The select element (size=1) and the input element with a list attribute are different elements, but have the same role: combobox. The problem should be fixed so that select elements are always output as listbox (or with another role), but never as combobox.

Examples of differences:
* input with list attribute: free text input possible, filtering of entries after text input, no navigation possible in closed state, visually indistinguishable from an input field in some cases, no quick navigation
* select: No free text input possible, no filtering of entries possible, navigation through list entries possible in closed state, visually always recognizable as select by triangle, quick navigation by entering a character

For blind users there is hardly a difference in functionality and operation between select size=1 and select size > 1, but a difference to input with list attribute.

Note: JAWS, for example, outputs the elements with different role names.

Note: The W3C does not use the combobox role in the ARIA Practices, but a button and the listbox role to build a select size=1 with ARIA (http://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html).

See also the discussion: https://github.com/w3c/html-aam/issues/46

**Comment by scottaohara** [comment]
Hi @JAWS-test 

per your reference, #46 is already an issue that exists and discussion is on going to determine if this mapping should be updated, and will likely be discussed at TPAC this year.  For those reasons I'm closing this issue as it's duplicative to the existing issue that already touches on these points, and more.

Thanks.
