### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aam#233]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by scottaohara** [comment]
* **What progress has your spec made in the last 12 months?**
Further rounding out expectations for elements and attribute mappings.  Working on rectifying and clarifying accessible name algorithms.  Many pieces are still in progress, but I've identified much of what I think needs to be completed and worked towards to move to CR.

* **Is anything blocking your spec from moving to CR?**
Issues I want to resolve before CR.  There is nothing _blocking_ these beyond time and resources to write tests and update the spec accordingly. While I have been doing work to resolve a good majority of these issues, any assistance in writing tests and contributing to the following is appreciated:

  - Updated naming algorithms and general guidance, which would resolve:
  #231, #227, #225, #211, #210, #209, #205, #179, #160, #158, #148, #134, #100, #29, #25, #238
  - HTML element removal, updates and additions which would resolve:
  #189, #188
  - Updating not mapped elements to indicate how they _could_ map, if given attributes that are important for accessibility
  #151, #143
  - Completion of attribute table for AX API
  #97 
  - Complete or remove any notes in the specification that are marked as "to do"


* **What do you want to achieve for your spec in the next two days (of breakout sessions)?**
While I will not be able to attend TPAC, I'm hoping that any issues / solutions that may be discussed and are applicable to the HTML AAM will be logged and PRs will be submitted.

**Comment by marcoscaceres** [comment]
Thanks @scottaohara for writing up the summary early. You get extra points! 🌟
 
Leaving this open, as using this for TPAC meeting planning.

**Comment by LJWatson** [comment]
@marcoscaceres  this is the status report from 2019. HTML AAM has been returned to the ARIA WG since then. @michael-n-cooper can we get this repo shifted over to the ARIA WG.  

CC @jnurthen  @joanmarie
