### ISSUE TITLE
Whitespace alone should be ignored in accName algorithms

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#238]
We need to make it clear in the specification that attributes that contribute to the accessible name of elements should be ignored if, when white space is trimmed, they return the empty string.

e.g. `alt=" "` should be treated the same as `alt=""`.

**Comment by pkra** [comment]
Related: https://github.com/w3c/accname/issues/55, whitespace is defined inconsistently across specs.

**Comment by scottaohara** [comment]
I'm closing this issue in favor of https://github.com/w3c/accname/issues/55

handling whitespace in accNames should be defined consistently over there, not with separate rules here.
