### ISSUE TITLE
HTML-AAM: consider adding note to style element that some CSS will change accessibiltiy tree

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#24]
_From @cyns on January 12, 2016 23:50_

For example, display:none removes elements from the accessibility tree.

_Copied from original issue: w3c/aria#198_

**Comment by asurkov** [comment]
Do we want to handle CSS styles mapping as part of HTML-AAM at all? If so, then we should consider to add a new section 'CSS styles mapping' like we have 'HTML elements mapping' and 'HTML attributes mapping'. Should we have a separate issue for this? @jasonkiss

**Comment by jasonkiss** [comment]
I believe there may still be an intention for something like a CSS-AAM, which would be my preference. A note regarding impact of some CSS in the `style` element makes sense, but I don't think we should start adding mappings for other technologies.

**Comment by jasonkiss** [comment]
Fixed with PR #114, thanks to @scottaohara.
