### ISSUE TITLE
Missing span and svg in AccName chapter

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#240]
I miss the elements <code>span</code> and <code>svg</code> in the chapter "5th Accessible Name and Description Computation". Shouldn't they be included in https://w3c.github.io/html-aam/#text-level-elements-not-listed-elsewhere or elsewhere?

**Comment by scottaohara** [comment]
`span` (among many other elements) will be covered when work is completed on #160 (it will be prohibited from receiving a name) and other issues related to naming that already exist.

`svg`s should be covered in https://github.com/w3c/svg-aam/

Thanks
