### ISSUE TITLE
Mistake in AccName for tr, td, th

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#247]
I think, at https://w3c.github.io/html-aam/#tr-td-th-elements-accessible-name-computation there should be step 2: "text content" and only step 3 "title".

In addition, the question would be whether the <code>abbr</code> attribute should be mentioned in this context, which does not serve as a label or description, but as a label of the heading during table navigation through the cells of the table.

**Comment by scottaohara** [comment]
closing as duplicate to #179

**Comment by JAWS-test** [comment]
Sorry I didn't check that out.

**Comment by scottaohara** [comment]
no problem
