### ISSUE TITLE
UIA figcaption is missing "Other properties" entry

### ISSUE THREAD

**Issue by carmacleod** [w3c/html-aam#249]
The [UIA entry for `figcaption`](https://w3c.github.io/html-aam/#el-figcaption) seems to be missing the following:

> Other properties: The LabeledBy property for the parent figure element points to the UIA element for the figcaption element

See "caption" and "legend" for example text.
See also that MSAA/IA2 and ATK do set up "...RELATION_LABEL_FOR with parent `figure` element" for `figcaption`.

@melanierichards Can you confirm that this is true?

**Comment by scottaohara** [comment]
per changes that are being made / will be made in #359, i'm closing this issue
