### ISSUE TITLE
When is legend label for fieldset?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#250]
For legend is defined:

* IA2_RELATION_LABEL_FOR with the parent fieldset
* The LabeledBy property for the parent fieldset points to the UIA element for the legend element. 
*  ATK_RELATION_LABEL_FOR with parent fieldset element 

I wonder if that's correct, since it doesn't make any statement about what happens 
* if several legends are in one fieldset or
* if the legend is not the first child element (as required by the specification: https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element)

**Comment by ZoeBijl** [comment]
According to the [`fieldset`-element documentation in the spec](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element) the name is taken from the first `legend` child element which also has to be the first child of the `fieldset`. Meaning that any other result is an author error. So yes, this is correct.

**Comment by JAWS-test** [comment]
I thought HTML-AAM should point out here that legend is only label for fieldset if it is the first child element. If it is not the first child element, it is ignored. Analogous to the distinction between header and footer scoped to the body element or not scoped to.

**Comment by ZoeBijl** [comment]
Did you run any tests in which this breaks?

**Comment by JAWS-test** [comment]
I'm afraid I don't understand what tests you mean? An empirical test with Screenreader? I'm happy to do that if you wish. But the specification should be correct, regardless of the screenreader output.

**Comment by JAWS-test** [comment]
So far I've only tested the following: https://github.com/FreedomScientific/VFO-standards-support/issues/233. But that doesn't include the question I raised here. See also: https://github.com/FreedomScientific/VFO-standards-support/issues/100

**Comment by ZoeBijl** [comment]
I’m not entirely sure what the error is with HTML-AAM. Could you point to the section in the spec where you saw the error? [5.5.1 fieldset Element Accessible Name Computation](https://w3c.github.io/html-aam/#fieldset-element-accessible-name-computation) reflects the HTML spec. Point four states that if the above conditions are false there is no accessible name.

**Comment by JAWS-test** [comment]
I didn't say it was an error. I was just wondering if the documentation should be more accurate: 
* legend may only be first child element
* https://w3c.github.io/html-aam/#fieldset-element-accessible-name-computation says that the first legend should be taken (but not that it should be the first child element)
* and https://w3c.github.io/html-aam/#html-element-role-mappings just says that the legend is the label of the fieldset (without notes on position). I.e. this part of the specification leaves open what happens if a fieldset has multiple legends.

If this is considered as not problematic, the ticket can be closed. I just thought the table should be as accurate as for header and footer.

**Comment by JAWS-test** [comment]
Checked the following file with JAWS 2019 and current Firefox ESR, IE 11, and Chrome:
* Firefox is halfway ok (browser automatically corrects the display if legend is not the first child)
* in IE 11 the output is completely wrong
* in Chrome the output of Tab Navigation seems relatively ok, but if you look into the element overview with INS+Ctrl+E, you can see that everything is wrong here as well
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>legend</title>
	</head>
	<body>
		<fieldset>
			<div>
				<legend>not a child</legend>
				<input aria-label=1>
			</div>	
		</fieldset>
		<fieldset>
			<input aria-label=2>
			<legend>not first child</legend>
			<input aria-label=3>
		</fieldset>
		<fieldset>
			<legend>1st child</legend>
			<legend>2nd child</legend>
			<input aria-label=4>
			<legend>4th child</legend>
			<input aria-label=5>
		</fieldset>
	</body>
</html>
```

**Comment by scottaohara** [comment]
closing this issue as there's no lack of clarity of how a `legend` should be mapped (here) or used (via the HTML spec).

That said, I will look into amending my WIP PR #232 to reference "first child" rather than just "child", to better match the HTML spec as per your second bullet in your opening question.  Your third bullet in your latest comment isn't accurate, as the fieldset accessible name algorithm does state "...use the subtree of the first such element. " which indicates that legends after the first are ignored because the accessible name for the fieldset has already been determined.

**Comment by scottaohara** [comment]
Let's be clear here though, stress testing how a browsers may expose and/or screen reader consumes invalid markup patterns is not indicative of a gap how HTML elements are mapped.

**Comment by JAWS-test** [comment]
It's true: The bugs also occur for things that are correctly specified in the specification, see https://github.com/FreedomScientific/VFO-standards-support/issues/315.
But if it's not exactly in the specification, you can't blame assistive technology for bugs.

**Comment by JAWS-test** [comment]
@scottaohara 
>  Your third bullet in your latest comment isn't accurate, as the fieldset accessible name algorithm does state "...use the subtree of the first such element. " which indicates that legends after the first are ignored because the accessible name for the fieldset has already been determined.

My comment refers as written to https://w3c.github.io/html-aam/#html-element-role-mappings and not to https://w3c.github.io/html-aam/#fieldset-element-accessible-name-computation where it is halfway correct.

And the table says (as described in detail in my very first statement): 
> For legend is defined:
> *    IA2_RELATION_LABEL_FOR with the parent fieldset
> *    The LabeledBy property for the parent fieldset points to the UIA element for the legend element.
> *    ATK_RELATION_LABEL_FOR with parent fieldset element

**Comment by scottaohara** [comment]
>you can't blame assistive technology for bugs

I didn't.  If anything I was saying that invalid markup patterns are to blame.

>The bugs also occur for things that are correctly specified in the specification

In that case not related to HTML AAM.  Bugs with browsers or AT or both.  It's good to try and determine which exactly so issues are filed in the correct place.


>My comment refers as written to https://w3c.github.io/html-aam/#html-element-role-mappings and not to https://w3c.github.io/html-aam/#fieldset-element-accessible-name-computation where it is halfway correct.

I know what your comment was referring to, but the opening of that section states:
>Where applicable, how an element participates in the computation of its own or another element's accessible name and/or accessible description is described in the Accessible Name and Description Computation section below.

In other words, you have to look to both sections to get the full picture.
