### ISSUE TITLE
Mapping of "open" on dialog seems wrong

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#265]
According to https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element:

> The open attribute is a boolean attribute. When specified, it indicates that the dialog element is active and that the user can interact with it.
 > A dialog element without an open attribute specified should not be shown to the user.

Dialogs -- at least on my platform -- are NOT things which can be expanded or collapsed. They can be shown or hidden/destroyed. When they're showing, they should be included in the accessibility tree; when they are hidden/destroyed, they should not be in the accessibility tree.

My *guess* is that this is the case for all the platforms.

Aside: The mapping for "open" on details seems right. Maybe this is just a copy and paste error for dialog?

**Comment by scottaohara** [comment]
agreed.  this is incorrect on `dialog`.  i'll pick this up asap.
