### ISSUE TITLE
Default level of h1-h6 and nested sectioning

### ISSUE THREAD

**Issue by Jym77** [w3c/html-aam#268]
As per https://w3c.github.io/html-aam/#el-h1-h6 the default level of `h1`-`h6` elements is the number in the tag. This does not correspond to the [outline algorithm](https://html.spec.whatwg.org/multipage/sections.html#outlines) of HTML (which, in very short, says that a `h1` inside a `section` is actually a `h2`).

As far as I can see, there was a voluntary change to the current version almost 2 years ago in #116, backed notably by the fact that browsers were doing the same.

From my recent quick tests, it looks that both Chrome, Edge and Firefox are rendering nested headings according to the outline algorithm (eg a `<section><h1>Foo</h1></section>` and a `<h2>Foo</h2>` are rendered exactly in the same way). So it seems that now browsers are implementing the outline algorithm correctly. This leads to inconsistencies between rendered content and outline exposed by assistive technologies.

Is it time to roll back on that change and have a default level set to the outline depth?

**Comment by stevefaulkner** [comment]
@Jym77 Hi, the outline algorithm has never been implemented in any browser apart from a subset of the styling. As a result the outline is in the process of being replaced with something that will hopefully be implemented by browsers, see discussion and PR https://github.com/whatwg/html/pull/3499 there is further background explanation and discussion references here: https://www.w3.org/wiki/HTML/Usage/Headings/h1only

**Comment by Jym77** [comment]
Thanks for the answer and the links 😄
