### ISSUE TITLE
rb element is not present in role mapping table

### ISSUE THREAD

**Issue by Jym77** [w3c/html-aam#281]
In the [HTML Element Role Mappings table](https://www.w3.org/TR/html-aam-1.0/#html-element-role-mappings), the `<ruby>`, `<rp>` and `<rt>` elements are listed, but the closely related `<rb>` is not.
Given that it's not in the Core AAM either, I guess it is missing and should be added (not sure with what values, however…)

**Comment by scottaohara** [comment]
It's not "missing", as it's purposefully not there.

from the changelog:
>30-Sept-2019: Remove mappings for rb and rtc elements as they are marked as obsolete in HTML. See GitHub issue #115 and pull request #253.

**Comment by Jym77** [comment]
Interesting. I have indeed missed that the ruby scripting had been simplified (removing `<rb>` and `<rtc>`).

**Comment by scottaohara** [comment]
It is still in HTML 5.2 / the HTML 5.3 draft.  But these elements were obsolete in the HTML Living Standard for years now.  And since the Living Standard is now the only HTML specification being worked on, this spec looks to it for determining what elements are obsolete.
