### ISSUE TITLE
Remove VARIANT section

### ISSUE THREAD

**Issue by aleventhal** [w3c/html-aam#285]
The VARIANT section that describes using a BSTR can now be removed:
https://www.w3.org/TR/html-aam-1.0/#use-of-msaa-variant-by-some-user-agents

I've coordinated this with Mozilla, JAWS and NVDA. This technique was necessary before IA2 existed, and screen readers no longer use it.

As a code cleanup, we're planning to remove the BSTR roles from Chrome, and only use enumerated roles.

**Comment by scottaohara** [comment]
Thank you for the heads up @aleventhal
