### ISSUE TITLE
HTML-AAM: should we have some general language for sub-doms?

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#3]
_From @cyns on January 12, 2016 18:33_

Canvas has an author-supplied sub-dom, which also maps into the accessibility api tree
The audio and video elements can have a whole tree of children if @controls is present. 
Should we add some general language to the document on how to handle these situations?

Here's what we have for UIA for canvas now. It seems inadequate. 
Control Type: Image 
NOTE: subdom elements will be mapped separately. 

_Copied from original issue: w3c/aria#141_

**Comment by jasonkiss** [comment]
Here's a first stab at elements that are typically complex widgets with sub-trees of accessible objects in certain APIs, and that we might want to address in a distinct section, instead of overwhelming the individual mapping table entries with this level of detail.

- audio
- video
- canvas
- input@type=color
- input@type=date
- input@type=file
- input@type=datetime-local
- input@type=number
- input@type=week

**Comment by asurkov** [comment]
Do you have ideas who to approach these? It seems the format is currently restricted to a table, which doesn't have flexibility of adding random stuff.

**Comment by jasonkiss** [comment]
We can add a distinct section to the document that discusses how compound widgets and their sub-trees are typically exposed across different UAs and a11y APIs. This section would replace the need to include this info with each element's mappings in the table.

**Comment by rahimabdi** [comment]
Closing, to be handled by two new issues:
- How to handle `<canvas>` sub-dom/fallback content: https://github.com/w3c/html-aam/issues/556.
- Propose UA requirements for complex `<input>` Shadow DOM parts and mappings (related to: [Review/revise mappings for input type=file · Issue #421 · w3c/html-aam (github.com)](https://github.com/w3c/html-aam/issues/421)): https://github.com/w3c/html-aam/issues/557.
