### ISSUE TITLE
Notes about algorithm for input type="image"

### ISSUE THREAD

**Issue by eps1lon** [w3c/html-aam#304]
1. > 2. Otherwise use alt attribute. 3. Otherwise use title attribute.

   Is the "otherwise" in point 3 similar to 5.1.1 where we have 
   > If the accessible name is still empty, then: use the control's title attribute.

   ? 
   Right now I can see no consistent language regarding these steps. It seems to me that every step only applies if the previous steps did not produce a name. But sometimes we have this explicitly mentioned and sometimes not.
2. >  the accessible name is a localized string of the word "Submit Query".

   This is followed by "If none of the above yield a usable text string there is no accessible name.". So  this localization could produce  an empty string? Wouldn't it be better to produce an accessible name in a foreign language rather than no name at all?
3. By spec this element cannot be labelled via `<label>`.
  However, a web-platform-test currently test this (https://github.com/web-platform-tests/wpt/blob/677c57c0e8816b0892cc3ae1c2772189b1bdcf65/accname/name_test_case_616-manual.html#L64-L65). Chrome 84 also allows labelling `<input type="image" />`. Should this test be removed or the spec updated to match implementations?

**Comment by scottaohara** [comment]
closing this as there are duplicate issues on these topics.

#423 was created to address the missing step for label elements

**Comment by eps1lon** [comment]
> closing this as there are duplicate issues on these topics.

@scottaohara  Could you link that? The linked PR does not address all points made in this issue.

**Comment by scottaohara** [comment]
https://github.com/w3c/html-aam/issues/414

**Comment by scottaohara** [comment]
have pulled over your OP into the newer issue
