### ISSUE TITLE
Broken anchor link for summary recommended mappings

### ISSUE THREAD

**Issue by 36degrees** [w3c/html-aam#308]
In [6.1.2](https://www.w3.org/TR/html-aam-1.0/#role-name-state-and-property-mapping), the anchor link 'recommended mappings for the summary element' (`#el-summary`) does not work.

It looks like there is an element on the page with the ID `el-summary` but possibly it's affected by the JavaScript on the mapping table?

https://github.com/w3c/html-aam/blob/a5637d23f91c6990cc857fe8a4098b71ec5990da/index.html#L6658

**Comment by scottaohara** [comment]
This is directly related to #255, and we've also removed this section from the specification.  so closing this one as its a symptom of the other issue / no longer relevant since the in-page link has been removed.
