### ISSUE TITLE
Option role dead link and clarification

### ISSUE THREAD

**Issue by AlexLloyd0** [w3c/html-aam#310]
The entry for [option](https://www.w3.org/TR/html-aam-1.0/#details-id-97) in the element-role mapping has a dead link for "list of options".

The [ARIA in HTML](https://www.w3.org/TR/html-aria/#el-option) spec links to https://html.spec.whatwg.org/multipage/input.html#attr-input-list. From my reading this means that `<option>` has a role of `option` if and only if it is a `<datalist><option>`.

Is it correct for `<select><option>` or `<select><optgroup><option>` not to have a role of `option`? As one data point Chrome and Firefox both expose `<select size=2><option>` as having `role=option`

**Comment by scottaohara** [comment]
the link is just not correctly remapping to https://html.spec.whatwg.org/multipage/form-elements.html#concept-select-option-list from the previous link that went to the W3C spec

**Comment by AlexLloyd0** [comment]
Thanks for updating. So an `<option>` has a role of option if it is in a list of options (`<select><option>` or `<select><optgroup><option>`) or in a datalist (`<datalist><option>`). But these are the only [contexts in which an option can be used](https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element).

So should HTML-AAM entry be for just `option`, as `in a list of options or represents a suggestion in a datalist` is implied by the HTML Standard?
