### ISSUE TITLE
mark role

### ISSUE THREAD

**Issue by pkra** [w3c/html-aam#316]
mark is listed with "No corresponding role" but ARIA now has a role mark.

**Comment by scottaohara** [comment]
Thanks @pkra but I have this covered with #229

just waiting on aria 1.2 to get to recommendation

**Comment by pkra** [comment]
Thanks, @scottaohara!

**Comment by scottaohara** [comment]
reopening this one since `mark` isn't in core aam/aria 1.2, but is part of 1.3
