### ISSUE TITLE
Mapping for hidden is wrong regarding CSS-visibility?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#319]
> If the element is no longer display: none or visibility: hidden then it does not map. 

If I understand it correctly, I can only override hidden with display and not with visibility (this is also how browsers handle it). Therefore the reference to visbility should be removed

**Comment by scottaohara** [comment]
yeh.  that could be more clear.   will make an update to clarify the intent of mentioning visibility hidden there
