### ISSUE TITLE
hgroup mappings do not seem correct

### ISSUE THREAD

**Issue by domenic** [w3c/html-aam#331]
The spec says "No corresponding role" / "Not mapped" for all mappings.

However, in my testing browsers instead map it the same as a no-accessible-name `section`, i.e. `ROLE_SYSTEM_GROUPING` / `IA2_ROLE_SECTION`. (I only tested MSAA.)

**Comment by scottaohara** [comment]
thanks @domenic, yup those are incorrect.  The element should map the same as a `div`
