### ISSUE TITLE
Why is outline depth involved in the level exposed for h1-h6?

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#336]
The HTML-AAM currently says the following for `h1`-`h6`:

> `heading` role, with the `aria-level` property set to the element's [outline depth](https://www.w3.org/html/wg/drafts/html/master/sections.html#outline-depth)

This surprised me. As a screen reader developer, I've always assumed that `h1` would expose `1`, `h2` would expose `2`, ... `h6` would expose `6`. And I think that's what the implementations currently do (right?). I also think that if I were a blind web author and I made a page using `h3` and my screen reader treated it as anything other than level 3, I'd report it as a screen reader bug.

**Comment by scottaohara** [comment]
yeh, this seems like something that shouldn't be there / would have been related to the outline algorithm which does not exist...

**Comment by joanmarie** [comment]
Let's pretend for a moment the outline algorithm 1) exists and 2) is already implemented in user agents so that implementing this mapping would just be a matter of calling that function within the accessibility code of user agents to expose the calculated value to ATs. Should we be turning an `h3` into something that is NOT level 3 if the author hasn't explicitly used `aria-level` on that `h3` to change it to something else? I'm thinking the answer is "no."

Apparently this has a huge history. See https://bugs.chromium.org/p/chromium/issues/detail?id=365070 (which just got assigned to me). I think implementing this exposure/mapping is a bad idea and likely not what screen reader users expect.

Perhaps we should bring this up at an ARIA WG meeting to see if we have consensus on whether or not potentially overriding heading levels by some algorithm is a good idea or a bad idea.

**Comment by scottaohara** [comment]
Yeh. I’ve spent quite a bit of time reviewing all the older threads up to the most recent comments / ideas of what to do with hgroup etc. 

There’s no real consensus on this and I also have major concerns with changing the heading level automagically on authors. 

Im curious what the wg thinks on this, as well, but I find the idea concerning.

**Comment by joanmarie** [comment]
@jnurthen Can we discuss this at the next ARIA WG meeting?

**Comment by scottaohara** [comment]
just a clarification on the above, `h1` is the only heading that would be 'expected' to change its rank per the above – becoming whatever rank was necessary depending on the nesting of `section` elements, for instance.  using `h2` to `h6` would remain those heading ranks as set by authors. 

edit: my memory was clouded by other discussions on how the outline algorithm could be implemented.  For instance [this HTML spec thread](https://github.com/whatwg/html/issues/83#issuecomment-380439343) where there was talk about avoiding the adjusting of h2 to h6.

Also of note is https://github.com/whatwg/html/issues/5002 where `hgroup` and how that would/could come into play here.

**Comment by scottaohara** [comment]
per ARIA wg call today, we will remove mention of this from the spec.

**Comment by scottaohara** [comment]
@joanmarie so interesting on this... but [HTML AAM has no mention of outline depth in it](https://w3c.github.io/html-aam/#el-h1-h6).

Following the link in the bug report though, I get to the old HTML to Platform Accessibility APIs Implementation Guide -  https://rawgit.com/w3c/html-api-map/master/index.html#el-h1-h6

This obsolete version of the spec somehow has today's date on it.... which sure makes it confusing. So, there's nothing for me to do here it seems, but do we need to do something with this obsolete version of the spec?

Will wait to hear what you think, and then close.

**Comment by joanmarie** [comment]
Huh. I guess I grabbed the text without looking to see that it wasn't actually in the HTML-AAM. Sorry about that!

The top of that document does have a giant "Beware" box pointing to the correct spec. But that isn't visible when you follow the link to the mappings.

Similarly, https://github.com/w3c/html-api-map is archived and points to the correct spec/repo.

@michael-n-cooper Thoughts on what (if anything) we should do regarding https://rawgit.com/w3c/html-api-map/master/index.html?

**Comment by jnurthen** [comment]
We could add the super annoying warnings (like https://www.w3.org/TR/2012/WD-proximity-20120712/ ) but we would need to unarchive the repository before making any changes.

I'd love a respec enhancement where someone could simply add a parameter to respec config which would add the super annoying warning AND change the "W3C Editors Draft" text to "Obsolete w3c draft" and change the color to something super weird so folks will notice it.
