### ISSUE TITLE
Republish spec "officially" to get auto-publish working again

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/html-aam#340]
As the specification is now part of the Aria WG, it needs to be "officially" republished as a WD for auto-publish to work (i.e., "change of deliverer"). 

@michael-n-cooper, could you please republish it? You might need to check what the Process says about specs adopted from another group if it can just go straight to WD or if it needs to be a FPWD.

**Comment by michael-n-cooper** [comment]
We don't use auto-publish, so we'll republish it manually eventually.

**Comment by jnurthen** [comment]
@michael-n-cooper is there a reason we can't auto publish? We want AAMs to go to that soon so if there is a reason we should work out what it is. Otherwise - can we get this pubished?

**Comment by michael-n-cooper** [comment]
In ARIA chair discussion today, we agreed to resume auto-publish of HTML-AAM asap and initiate it for other AAMs as soon as we're sure there aren't gotchas.

**Comment by marcoscaceres** [comment]
Sounds great! Give me @ shout if I can be of any help or want me to review anything.

**Comment by michael-n-cooper** [comment]
Spec was published today. I *think* auto-publish will just resume, but not sure. If I need to update the token or decision URI it'll take a few days to complete the CfC.

**Comment by marcoscaceres** [comment]
Thanks for the update @michael-n-cooper! Checking the logs and output, looks like it's working well already! 🥳
