### ISSUE TITLE
Mapping of svg/math tags in non-SVG/non-MathML namespaces

### ISSUE THREAD

**Issue by fred-wang** [w3c/html-aam#344]
cc @asurkov 

The HTML-aam spec defines "how user agents map HTML elements" which I interpret it as elements in the HTML namespace ( see https://html.spec.whatwg.org/multipage/infrastructure.html#html-elements ). However, it also describes mapping for the `<svg>` and `<math>` elements which are *not* HTML elements, even if they are described in HTML5 (note that they are respectively put in the SVG and MathML namespaces by the parser).

Mapping for `<svg>` is actually already defined in svg-aam and it was suggested that html-aam cross-references it in https://github.com/w3c/html-aam/issues/43#issuecomment-253109071

Mapping for `<math>` is not defined in mathml-aam but it looks like this is the place where it should be ( see https://github.com/w3c/mathml-aam/issues/9 ) 

If you want to keep `<svg>` and `<math>` in the HTML-aam spec, I believe you should be explicit about namespaces to avoid confusion. For example, I noticed that Chromium seems to only check the local name to map tag `math` to role `math`, which means it currently performs the mapping for non-MathML `<math>` tag too: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/accessibility/ax_node_object.cc;l=1005;drc=4b13e65c914599d4be74a9f4db257fa1218b865b

**Comment by scottaohara** [comment]
SVG points to the graphics aam where the graphics-document role is defined (svg aam points to this doc as well with their mapping of `svg`).  

A comment in the table saying to refer to also refer to svg-aam for more mappings related to svgs and their descendants can be added.

Similarly, the math element points to core aam where the math role is defined.  A comment, similar to what's described above for svgs, can be made to point to mathml aam for additional mappings related to math elements / their descendants.

@asurkov, @joanmarie or @stevefaulkner do any of you see a need for additional updates?   Would it be better to not reference the wai-aria role at all and just point to the necessary specifications for math (core aam, mathml) / svg (svg aam, graphics aam)?

**Comment by fred-wang** [comment]
Just to be clear, my point is that this spec seems to be about mapping HTML elements, but `<math>` and `<svg>` are not such elements. So MathML/SVG namespaces should be explicit, or they should be moved to their respective aam specs.

**Comment by stevefaulkner** [comment]
> Would it be better to not reference the wai-aria role at all and just point to the necessary specifications for math (core aam, mathml) / svg (svg aam, graphics aam)?

yes
