### ISSUE TITLE
HTML-AAM: role=status is not a good match for output element

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#36]
_From @cyns on March 18, 2016 23:29_

The output element isn't exactly a status bar. I think a more generic mapping (group?) and a live region is better. I've aleady updated the UIA mapping here, but I don't think this is a good mapping for the other APIs either.

_Copied from original issue: w3c/aria#309_

**Comment by jasonkiss** [comment]
_From @cyns on March 30, 2016 19:40_

@stevefaulkner @jasonkiss @asurkov @Joanmarie @cookiecrook @klown 
I'd like to update this sooner than later. What do you think about removing the mapping from the html output element to role=status? While they have some similarities (polite live region), I think calling an output a status bar is confusing.

**Comment by jasonkiss** [comment]
_From @stevefaulkner on March 30, 2016 21:10_

@cyns looking at this related bug may be helpful https://www.w3.org/Bugs/Public/show_bug.cgi?id=26135 there has never been in rough concensus on the correctness of the current mapping

**Comment by jasonkiss** [comment]
_From @cookiecrook on March 31, 2016 4:46_

> The output element isn't exactly a status bar.

I consider "status" more general than "status bar" ("bar" implies a particular presentation and usage) so I don't have a strong aversion to using status as the default role for the output element. 

> I think calling an output a status bar is confusing.

Confusing to whom? Most web developers won't be aware of "element default roles" at all. Can you be more specific about why you want the change?

**Comment by jasonkiss** [comment]
_From @cyns on April 23, 2016 21:37_

@cookiecrook the aria status role is mapped to Status Bar on IA2 and ATK. It was mapped to that for UIA as well, but I changed it to a group with a polite live region. It may not have originally been intended to be a status bar, but several platforms treat it as such.

I created tracker issues about the aria mappings

**Comment by jasonkiss** [comment]
_From @cyns on April 23, 2016 21:39_

https://www.w3.org/WAI/ARIA/track/issues/1024

**Comment by jasonkiss** [comment]
_From @asurkov on August 11, 2016 20:21_

I'm not sure whether role=status is a good match, which is defined as
"A type of live region whose content is advisory information for the user but is not important enough to justify an alert"
and HTML output as
"The HTML <output> element represents the result of a calculation or user action."
which is not necessary same.

However it doesn't affect on mapping, since role='status' is mapped to role section plus polite live region in IA2/MSAA/ATK afaik.

**Comment by jasonkiss** [comment]
_From @klown on August 11, 2016 21:0_

@asurkov 

>  it doesn't affect on mapping, since role='status' is mapped to role section plus polite live region in IA2/MSAA/ATK afaik.

Current [Core-AAM mappings](https://rawgit.com/w3c/aria/action2102/core-aam/core-aam.html#role-map-status) are to `ROLE_SYSTEM_STATUSBAR` (MSAA/IA2) and `ROLE_STATUSBAR` (ATK/AT-SPI) plus polite and status live region info.  The [ARIA 1.0 test case](https://www.w3.org/WAI/PF/testharness/testresults?testsuite_id=1&testcase_id=63) passed using those mappings.

**Comment by jasonkiss** [comment]
_From @asurkov on August 12, 2016 14:45_

oh, then it's a bug, HTML output is not a status bar, while ROLE_SYSTEM_STATUSBAR is:

"The object represents a status bar, which is an area at the bottom of a window and which displays information about the current operation, state of the application, or selected object. "

https://msdn.microsoft.com/en-us/library/windows/desktop/dd373608(v=vs.85).aspx

I'm getting a stronger feel to keep HTML mapping on its own, not delegating to ARIA core. Same way we did before.

**Comment by asurkov** [comment]
@jasonkiss should role='status' be removed from output's WAI-ARIA mapping? and then IA2/ATK/AX mappings be provided?

**Comment by jasonkiss** [comment]
I think mapping to role=status makes sense for `output`, but that the CORE-AAM mappings for role=status should be updated to avoid direct association with a status bar (as opposed to a more general live region type area). 

So MSAA+IA2 should not map role=status to ROLE_SYSTEM_STATUSBAR. 

But the definition for ATK_ROLE_STATUSBAR is "An object which reports messages of minor importance to the user" and does not specify the "status bar" type presentation that the MSAA role does. So it might be okay for ATK.

**Comment by asurkov** [comment]
Is there open issue for core-aam part? Do we have anything left to fix on our side?

**Comment by klown** [comment]
@asurkov wrote:
> Is there open issue for core-aam part? Do we have anything left to fix on our side?

@cyns raised [ISSUE-1024](https://www.w3.org/WAI/ARIA/track/issues/1024) in tracker against Core-AAM 1.1, asking if the MSAA/IA2 and ATK/AT-SPI [mappings](https://rawgit.com/w3c/aria/action2102/core-aam/core-aam.html#role-map-status) are correct.

As noted elsewhere, these mappings were tested in the 1.0 time frame, and the [tests passed](https://www.w3.org/WAI/PF/testharness/testresults?testsuite_id=1&testcase_id=63).  So, it's likely there is nothing to fix here.

But, to be sure, can you confirm the MSAA/IA2 mapping, @asurkov?  @Joanmarie, what about the ATK/AT-SPI mapping?

**Comment by asurkov** [comment]
In Firefox HTML:output is exposed as IA2_ROLE_SECTION/ATK_ROLE_SECTION and 'polite' live region attribute.

**Comment by klown** [comment]
Thanks @asurkov 

> In Firefox HTML:output is exposed as IA2_ROLE_SECTION/ATK_ROLE_SECTION and 'polite' live region attribute.

The Core-AAM [issue](https://www.w3.org/WAI/ARIA/track/issues/1024) is whether the [mappings for role="status" ](https://rawgit.com/w3c/aria/action2102/core-aam/core-aam.html#role-map-status )are correct.  Are they?

**Comment by asurkov** [comment]
As far as I can tell that Firefox follows the current mapping for IA2 and ATK in case of role='status'. However I'm not sure how much that is correct. The mapping shouldn't be that different between platforms, and the role='output' definition says 'but not necessarily presented as a status bar', which means that statusbar role is not the best match.

**Comment by scottaohara** [comment]
Things seem to have shifted from this issue originally being filed...

[Should status role be mapped to Status Bar?](https://www.w3.org/WAI/ARIA/track/issues/1024)  - was closed and marked as wontfix.

2 and a half years since the last comment here:
Firefox is the only modern browsers that doesn't expose `output` as a live region. [An issue was filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1563598).

Per the above, closing this issue.
