### ISSUE TITLE
Section element table should have platform-specific details removed or possibly corrected

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#361]
The current mappings for `section` say:

> `region` role if the `section` element has an accessible name. Otherwise, the `generic` role.

And the Core-AAM has mappings for both scenarios.  So I think the platform-specific stuff can be removed. (Aside: The interfaces listed for IA2 and ATK don't really need to be stated here or in any table in the Core-AAM. The web would literally be completely broken if elements with text or child elements failed to implement those interfaces).

If the platform-specific entries are to remain for now in the HTML-AAM, the UIA entry seems to conflict with what is in the Core-AAM. Is the Localized Control Type really "section"?

**Comment by scottaohara** [comment]
makes sense.  i agree those shouldn't be necessary if just pointing to core aam
