### ISSUE TITLE
Remaining elements to revise mapping

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#373]
Closing #229, #183 and #346 in favor of this new issue to simplify.

The following elements should map to `generic`, but we will either need a call out here, or in CORE AAM how AT should treat an 'inline' vs a 'block'/other display type `generic` (if not doing something with https://github.com/w3c/aria/pull/996).

- [x] `area` no `href` 
- [x] `b`
- [x] `i`
- [x] `data`
- [x] `samp`
- [x] `kbd`
- [x] `pre`
- [x] `q`
- [x] `s`
- [x] `small`
- [x] `u`
- [x] `var`  (or maybe this is also `role=code`?  )

the following need to be changed to 'no corresponding role' until their mappings can be finalized - covered in #376
- [x] `dd` 
- [x] `dt`

questions on the following
- [x] `bdi` / `bdo` (change to `generic` or leave as a 'no corresponding role'?)
- [x] `cite` (change to `generic` or leave as a 'no corresponding role'?)
- [x] `abbr` (change to `generic` or leave as a 'no corresponding role'?)
- [x] `address` (change to `generic` or map to `group`?)
- [x] `figcaption` still map to `caption` even though it won't provide the `figure` a name anymore?  (i think it might be ok, but want others opinions)
- [x] `label`, this stay as no corresponding role?  We aren't moving forward with a `label` role, are we?  Could this actually be another instance of `caption`?  is this a `generic` if not?
- [x] `legend` same as above?

**Comment by jnurthen** [comment]
Proposed Deep Dive for June 30

**Comment by scottaohara** [comment]
From today's deep dive:

area no href - generic
b - generic
i - generic
kbd - new role (not mapped presently) - **create new issue**
pre - generic
q - generic
s - map to del? - **create issue.** 
small - generic
u - generic
var - probably code? but **create new issue.**

bdi/bdo - generic
cite - **new issue to discuss if this needs a new role.**
address - group

**create a new issue** to merge caption, legend, and label as they all do the same thing at a high level - identify content that names another element


while `<b>`, and `<i>` were resolved to map to generic today, there was discussion about how end users will perceive no different visual representation to those element compared to `<strong>` and `<em>` - which are not `generic`. 
'semantically' these are different from an HTML markup / "semantics" point of view.  from an end user point of view, they're interchangeable.  At some point I should create an issue concerning these elements to see if the HTML editors would have any concerns with us also mapping `b` and `i` to `strong` and `emphasis`.

**Comment by scottaohara** [comment]
Other no corresponding role elements, such as iframe, audio, video, etc. likely need some sort of role for implementors, but not for authors, if not one for both.  but those would also need their own issues (which may already exist in ARIA).  This is specifically for accName purposes to help determine what elements can be named.  

To help, HTML AAM could also indicate on a per-element basis which elements are namable vs not in the mapping tables.  This goes along with other updates that need to be done to the accName section to simplify/clarify that section of the spec.
