### ISSUE TITLE
Screen reader announces "invalid data" for radio button when it's required and not checked on initial render on Chrome

### ISSUE THREAD

**Issue by Benny-zliu** [w3c/html-aam#394]
Hello!

This was an issue originally filed on Chromium bug tracker site. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1311764

I was advised to open an issue for this repo.

Below is the issue description, please let me know if the issue description need any updates or you need additional info. Thanks!

-------
Steps to reproduce the problem:
1. Go to https://jsfiddle.net/fdcz2tny/
2. Turn on screen reader (I was using VoiceOver)
3. Try to focus on the "radio" radio button on the rendered page

Expected
Screen reader is expected to announce "* radio required radio button 1 of 1"

Actual
Screen reader announces "* radio required invalid data radio button 1 of 1"

This behavior was observed on Chrome, but not on Safari and Firefox.

**Comment by JAWS-test** [comment]
Related: https://github.com/w3c/wcag/issues/1769 and https://github.com/w3c/aria/issues/1470

**Comment by JAWS-test** [comment]
Not sure if the issue is correct here. Where does HTML AAM regulate something about this misbehavior?

The HTML specification defines when a form field is considered invalid.

Problem here is that browsers display fields visually as valid but output to the API as invalid.

So this is either a bug in the HTML specification or in the browser.

To effect a change seems to be difficult...

**Comment by stevefaulkner** [comment]
@Benny-zliu if a control (or in the case of `<input type=radio>` any in the group)  has it's required state set using the HTML `required` attribute it is also exposed as invalid, until it's [validation constraints](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constraints) have been met. In the case of  `<input type=radio>` one of the buttons in the group is selected. 
As @JAWS-test states

> The HTML specification defines when a form field is considered invalid.

**Note:** Safari does not appear to expose any field with `required` as invalid, contrary to other browsers

**Comment by Benny-zliu** [comment]
Thanks for the inputs. I get it that the form field is exposed as invalid according to the validation constraints.

Is there specifications on how browsers should be behave in this case, or is it totally up to the browsers? Sorry if the question doesn't fall into the purview of this community.

**Comment by stevefaulkner** [comment]
@Benny-zliu 

> Is there specifications on how browsers should be behave in this case

The HTML AAM is the place where it should be defined, based on what the HTML spec says. I don't see any mention of the invalid state (and the `required` attribute points to the `aria-required` attribute implementation, which does not take validation constraints into account) @scottaohara let's discuss how this can be improved.

**Comment by pshaughn** [comment]
This seems to overlap https://github.com/whatwg/html/issues/7848 (where conversation has largely converged to a consensus the behavior is more of an HTML-AAM rather than core HTML one).
