### ISSUE TITLE
Editorial: broken links to IAccessible2 and AT-SPI docs in references

### ISSUE THREAD

**Issue by cyns** [w3c/html-aam#408]
In the references section of html-aam, the links to the Linux foundation documentation for IAccessible 2 are broken. 

This URL is 404
[IAccessible2]
[IAccessible2](https://www.linuxfoundation.org/collaborate/workgroups/accessibility/iaccessible2). Linux Foundation. URL: https://www.linuxfoundation.org/collaborate/workgroups/accessibility/iaccessible2

**Comment by jnurthen** [comment]
Do you know where it should go?
These refs come from specref and any updates need to be filed as issues at https://github.com/tobie/specref

**Comment by jnurthen** [comment]
Is this the right link? https://accessibility.linuxfoundation.org/a11yspecs/ia2/docs/html/

**Comment by jnurthen** [comment]
From trawling the internet archive and the linuxfoundation site
https://wiki.linuxfoundation.org/accessibility/iaccessible2/
appears to be the same resource as 
https://web.archive.org/web/20160122032422/http://www.linuxfoundation.org/collaborate/workgroups/accessibility/iaccessible2

**Comment by cyns** [comment]
AT-SPI links are also broken
[AT-SPI]
[Assistive Technology Service Provider Interface](https://developer.gnome.org/libatspi/stable/). The GNOME Project. URL: https://developer.gnome.org/libatspi/stable/

**Comment by cyns** [comment]
> Do you know where it should go? These refs come from specref and any updates need to be filed as issues at https://github.com/tobie/specref

I don't know

**Comment by jnurthen** [comment]
filed https://github.com/tobie/specref/issues/710

**Comment by cyns** [comment]
Same issue in core-aam https://github.com/w3c/core-aam/issues/121

**Comment by jnurthen** [comment]
well yeah - it is the same reference pulled from specref

**Comment by jnurthen** [comment]
created https://github.com/tobie/specref/pull/711

**Comment by scottaohara** [comment]
closed from merging #409
