### ISSUE TITLE
[HTML AAM] Mapping of 'form' element to ARIA 'form' role should only be done when element has a label

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#45]
_From @richschwer on April 26, 2016 19:58_

The form element in HTML should only map to the ARIA form role if it has a label. Otherwise, it maps to the normal form mapping on the platforms. The reason is backward compatibility for old code that does things like embed a single button in form or make form the container for all the content in the page besides <body>

_Copied from original issue: w3c/aria#353_

**Comment by jasonkiss** [comment]
Given that HTML-AAM defers to Core-AAM where it can, will wait for Core-AAM to resolve its [issue #514](https://github.com/w3c/aria/issues/514) before following suit.

**Comment by scottaohara** [comment]
Noting Core-AAM issue now exists at [Add conditional platform mappings for nameless forms #11](https://github.com/w3c/core-aam/issues/11)

**Comment by scottaohara** [comment]
Closing this issue as HTML AAM is mapping to the correct roles / definitions in Core AAM if an HTML form has a name or not. 

cc @carmacleod as we spoke about this today.
