### ISSUE TITLE
Verify contenteditable mapping for AX API and fix AXtextArea typo

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#455]
In reviewing https://github.com/w3c/aria/pull/1830 during the ARIA wg call today, ARIA is adding more clarity that elements that are contained within a textbox need to be presentational.  But, Webkit presently has a mapping for `contentedtiable` to be a `role=textbox`.  bringing that up on the call today, it was mentioned that's probably not what should be happening here.

cc @cookiecrook

**Comment by cookiecrook** [comment]
Will discuss with Scott first, then other Apple engineers.

**Comment by cookiecrook** [comment]
There is acknowledgement that there are benefits to moving the AT support away from role in this context, but for now, de-coupling that engine and AT code is a major undertaking and therefore not a top priority. So let's keep the contenteditable mapping as-is and use this Issue to:

1. File and link the relevant [WebKit issue](https://webkit.org/b/251404) that may eventually happen along with a VO change in the internal tracker.
2. Fix  the capitalization typo in the mapping. `AXtextArea -> AXTextArea`

**Comment by cookiecrook** [comment]
I don't have the right permissions to change HTML-AAM issue titles. Can we make this "Verify contenteditable mapping for AX API and fix AXtextArea typo"

**Comment by cookiecrook** [comment]
WebKit issue: https://webkit.org/b/251404
