### ISSUE TITLE
Inaccurate mapping for select and input with list attribute

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#473]
Both select and input with list attribute maps to combobox. But this is not completely correct, because there are two different forms of combobox:
* select = combobox at a generic element (like div) = drop-down list.
* input with list = combobox at input = combined input field

The change should be made as soon as https://github.com/w3c/core-aam/issues/111 was successful

**Comment by cookiecrook** [comment]
Seems very similar to #467

**Comment by cookiecrook** [comment]
Also `<select multiple>` maps to listbox.

**Comment by cookiecrook** [comment]
@JAWS-test unless you can clarify how this is different from current mapping and the other linked issue, I'll close this one. Thanks.

**Comment by JAWS-test** [comment]
Difference to https://github.com/w3c/html-aam/issues/467: you describe differences between Windows and Mac, I describe differences between different manifestations of the element (independent of Mac and Windows)

Difference to the current mapping: I have described above. Is the description unclear?

**Comment by cookiecrook** [comment]
I still think we're using different terminology to discuss the same thing. 

Quoting me from #467:
 > > A true combobox is always (or almost always?) rendered as a text field with text-carat insertion and an associated menu. That's not the case for simple <select> menus

Quoting you from above:
> > input with list = combobox at input = combined input field
> Difference to the current mapping: I have described above. Is the description unclear?

Yes, it's unclear. I assume the word equation means something about typeahead comboboxes are different from select menus. If so, I agree, and included that as a primary point in #467. If that's not what you mean, please expand the word equations into sentences. Thanks.

**Comment by cookiecrook** [comment]
struggling to get that formatting right. hmmm. Trying as a new post.

**Comment by cookiecrook** [comment]
I still think we're using different terminology to discuss the same thing. 

Quoting me from #467: 

> A true combobox is always (or almost always?) rendered as a text field with text-carat insertion and an associated menu. That's not the case for simple <select> menus.

**Comment by cookiecrook** [comment]
Quoting you from above: 

> input with list = combobox at input = combined input field

Yes, it's unclear. I assume the "combined input field" means something about freeform text field comboboxes being different from non-freeform select menus, even those with typeahead. If that's what you meant, I agree, and included that as a primary point in #467. If that's not what you meant, please expand the word equations into sentences. Thanks.

**Comment by JAWS-test** [comment]
Your issue is about differences between the Mac and Windows world - for the same element (select without multiple and size attribute).

My issue is about differences of 2 HTML elements (select and input with list attribute). These two elements are different, no matter if I have a Mac or a Windows computer.

**Comment by JAWS-test** [comment]
There are 2 completely different problems regarding the same element (select without size and multiple attribute). One problem results from the fact that a select on Mac is a button with menu and menuitem and in Windows it is a combobox with listbox + option. The other problem results from the fact that until ARIA 1.1 a combobox was only used for input with list attribute and a select had the mapping to listbox. So I could distinguish the two elements. In the meantime both elements map to combobox.

If you want to combine both problems in your issue, feel free to close my issue

**Comment by cookiecrook** [comment]
Up to @scottaohara if these should be addressed as one issue or two.

**Comment by scottaohara** [comment]
i prefer a single issue. i'll close this and comment in the other one to indicate that when addressing that issue, the discussion of this one is considered.
