### ISSUE TITLE
Why are <b> and <s> mapped to semantic roles, but <i> is not?

### ISSUE THREAD

**Issue by cookiecrook** [w3c/html-aam#475]
Why are `<b>` and `<s>` mapped to semantic roles (`strong` and `deletion`), but `<i>` is `generic`?

FWIW, I think all the style-based tags should be generic, but perhaps we can settle on consistency, one way or the other. Either `<i>` should be `emphasis`, or `<b>` and `<s>` (maybe more) should be `generic`, right?

**Comment by scottaohara** [comment]
The answer is because I made a mistake :)

**Comment by stevefaulkner** [comment]
@scottaohara  Can you explain the reasoning for collapsing the semantics of `b/strong` and `i/em` as they are defined in [HTML as representing different things](https://html5accessibility.com/stuff/2023/02/19/representation-of-style/)

**Comment by cookiecrook** [comment]
I (and maybe Scott) argued for b and i to map to generic, but the ARIA WG went a different way. @michael-n-cooper @joanmarie or @jnurthen may be able to find the specific decision. 

They’d be interested to know that ARIA WG decision conflicts with the primary standard.

**Comment by scottaohara** [comment]
just mentioning here that I've commented in the new issue that James created, so per anyone cc'd in the previous comment, may be worth reading that issue too.

**Comment by cookiecrook** [comment]
Closing the loop. 

The AAM change was rolled back with:
- #483

The test change was rolled back with:
- https://github.com/web-platform-tests/wpt/pull/39911
