### ISSUE TITLE
Incorporate host-language unique `computedrole` string for reserved native elements with no direct ARIA equivalent

### ISSUE THREAD

**Issue by cookiecrook** [w3c/html-aam#511]
Incorporate Example 3 in https://w3c.github.io/core-aam/#roleMappingComputedRole

> When host language elements do not have an exact or equivalent mapping to a valid, non-abstract role, the related Accessibilty API Mapping extension specification MAY specify a unique computedrole string as the return value for interoperability testing purposes, such as `<video> -> "html-video"` in [[HTML-AAM](https://w3c.github.io/core-aam/#bib-html-aam)]. However, authors MUST NOT use any host-language-prefixed computedrole string in the role attribute (such as html-video), unless the token also matches valid, defined role (such as dpub-chapter). User Agents MUST ignore any abstract or invalid role token.

> #### EXAMPLE 3
```html
<video> <!-- computedrole returns "html-video" -->
<main role="html-video"> <!-- Author error. computedrole returns "main" -->
```

**Comment by cookiecrook** [comment]
I thought this one existed already, but I could not find it in HTML-AAM. I was probably thinking of a related tracker in the main ARIA spec repo.

**Comment by cookiecrook** [comment]
Some related discussion in the following:
- https://github.com/w3c/aria/issues/529
- https://github.com/w3c/aria/issues/1887

Related spec commit: 
- https://github.com/w3c/core-aam/commit/5d6012b746ffed1778204f9bfc837a70d966e741

**Comment by scottaohara** [comment]
Looks like the computed role content got deleted when HTML AAM was converted form the details/summary/table layout to just tables. 

I'll get these all back into the spec with the PR to address this.

**Comment by spectranaut** [comment]
Ugh, sorry @scottaohara, I guess that was my fault :(

**Comment by scottaohara** [comment]
No more your fault than mine, since I didn’t catch it
