### ISSUE TITLE
HTML-AAM: how to treat <img alt> with no value

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#55]
_From @cyns on May 23, 2016 19:14_

Should &lt;img alt&gt; be treated like &lt;img alt=""&gt; (mapped to role=presentation) or like &lt;img&gt; with missing alt attribute?

_Copied from original issue: w3c/aria#381_

**Comment by jasonkiss** [comment]
_From @cyns on May 23, 2016 19:15_

@stevefaulkner @jasonkiss this implementation question came up today. I'm inclined to treat alt with no equals or value as a missing alt, rather than an empty string. What do you think?

**Comment by jasonkiss** [comment]
_From @AmeliaBR on May 23, 2016 20:3_

Browser dev tools do not distinguish between alt attribute set to an empty string ( `<img alt="" />` ) and alt attribute without a value (`<img alt />`).  Chrome normalizes both to the Boolean format (without a value), while Edge and Firefox normalize both to the empty string version.

I haven't tested whether there are currently any differences in how they are exposed to the accessibility tree.  However, I am fairly confident that authors would expect them to be interchangeable.  So, to Cynthia's question: alt without a value should be treated like alt with an empty string, which is different from no alt at all.

**Comment by jasonkiss** [comment]
_From @AmeliaBR on May 23, 2016 20:10_

PS: [Test case as JSBin output page](http://output.jsbin.com/gisulebafu)

**Comment by annevk** [comment]
FWIW, I think this can be closed. As mentioned above, you cannot distinguish `<img alt>`, `<img alt=>`, `<img alt= >`, `<img alt=''>`, and `<img alt="">`.

**Comment by AmeliaBR** [comment]
The only question, to me, is whether there should be clarifying language in the spec. If browser devs weren't confident whether an empty string was equivalent to no value, I don't think we can assume that web authors will know it automatically.

**Comment by annevk** [comment]
If the HTML Standard is confusing about how the DOM is created, that'd be a good place to clarify that, I think, not here. This should just operate on the DOM.

**Comment by AmeliaBR** [comment]
For HTML-AAM, I'd suggest changing [this heading](https://w3c.github.io/html-aam/#el-img-emptyalt) from:

> img (alt attribute value is an empty string, i.e. `alt=""`)

to

>  img (alt attribute value is an empty string, i.e. `alt=""` or `alt` with no value in the markup)

so that there is a clarification right where it is used.  As @annevk said, the two markup forms are equivalent to the HTML parser, but it is confusing to call out one but not the other.

Perhaps similar clarifications would also be appropriate in the HTML spec; I'll comment on that issue separately.

**Comment by chaals** [comment]
@AmeliaBR see https://github.com/w3c/html/issues/1243

**Comment by jasonkiss** [comment]
Thanks @annevk and @AmeliaBR for the discussion and suggested clarification. Have implemented in a967061. Closing.
