### ISSUE TITLE
Mappings for class and id attributes missing

### ISSUE THREAD

**Issue by aleventhal** [w3c/html-aam#553]
Both of these say "Not mapped" across all platforms:
https://w3c.github.io/html-aam/#att-class
https://w3c.github.io/html-aam/#att-id

Here are the mappings:
ATK and IA2: object attributes "class" and "id".
UIA: UIA_ClassNamePropertyId and UIA_AutomationIdPropertyId
Mac: AXDOMClassList and AXDOMIdentifier

**Comment by smockle** [comment]
Opened https://github.com/w3c/html-aam/pull/559 to add these mappings.
