### ISSUE TITLE
HTML-AAM: MSAA+IA2 for header and footer with ancestor body should match

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#59]
_From @jasonkiss on September 28, 2016 3:30_

`footer` with ancestor body has MSAA `ROLE_SYSTEM_GROUPING` and `IA2_ROLE_FOOTER`. Shouldn't `header` with ancestor body also take `ROLE_SYSTEM_GROUPING` in addition to `IA2_ROLE_HEADER`?

@asurkov?

_Copied from original issue: w3c/aria#438_

**Comment by asurkov** [comment]
these should be same I'd say. Where can I check out latest HTML version? since it was moved to a new repo if I understand right.

**Comment by jasonkiss** [comment]
https://rawgit.com/w3c/html-aam/master/index.html

**Comment by asurkov** [comment]
right, definitely they should be same

**Comment by asurkov** [comment]
it's probably not big deal to list applicable MSAA role if we have IA2 ones, but just to keep the mappings in sync https://github.com/w3c/html-aam/commit/50f7d5a6fb6e5a1c9b97e33f3c6ac4e308489dd5
