### ISSUE TITLE
HTML-AAM: should <dfn> map to aria role=term?

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#6]
_From @cyns on January 12, 2016 18:37_

_Copied from original issue: w3c/aria#144_

**Comment by jasonkiss** [comment]
I don't think so. `<dfn>` represents the defining instance of a term, while the definition role represents the definition of a term or concept. However, we might want to map <dfn> to [role=term (ARIA1.1)](http://w3c.github.io/aria/aria/aria.html#term) depending on how that role gets mapped

**Comment by jasonkiss** [comment]
See related [ARIA issue #455](https://github.com/w3c/aria/issues/455)

**Comment by joanmarie** [comment]
@jasonkiss, regarding this:

> However, we might want to map to role=term (ARIA1.1) depending on how that role gets mapped

I'm thinking we do.

**Comment by jasonkiss** [comment]
Thanks, @joanmarie. I'd sure like to.

I see that the ATK mapping for the `term` role is ATK_ROLE_DESCRIPTION_TERM, [whose definition](https://developer.gnome.org/atk/stable/AtkObject.html#AtkRole) is "An object that represents the term, or name, part of a term-description group in a description list." 

Doesn't that definition assign the `term` role some list semantics, even if only description-list? I see that you closed related [ARIA issue#455](https://github.com/w3c/aria/issues/455), so perhaps I'm misreading/misunderstanding? As I read the current `term` role mappings, it's now just ATK that has list-related semantics for `term` <smile>.

**Comment by jasonkiss** [comment]
I should add that, while the ARIA spec indicates the `term` role as being conceptually related to the HTML `dt` element, the [definition of the `term` role](http://w3c.github.io/aria/aria/aria.html#term) doesn't include any mention of lists, definition/description or otherwise.

**Comment by joanmarie** [comment]
@jasonkiss: If need be, I can update the ATK docs. I didn't see creating a brand new ATK role when this existing role would do. Then poof! No more list semantics. :smile: Would that address your concerns?

**Comment by joanmarie** [comment]
@jasonkiss: The ATK documentation has just been updated via the following commit: https://git.gnome.org/browse/atk/commit/?id=4a2632d. Please note that this change will not show up in the official docs until a new ATK release is done. That won't be too long, but you may have a few weeks to wait. If you must have the change show up in the web-based developer docs before you feel comfortable proceeding, let me know and I'll see if I can convince my colleague to do a special release for you.

Related to the above: The change will show up in the "unstable" docs first. That URL is: https://developer.gnome.org/atk/unstable/AtkObject.html#AtkRole (i.e. s/stable/unstable/). For it to show up in the URL for "stable", you'll need to wait until at the end of the current release cycle.

**Comment by jasonkiss** [comment]
@joanmarie: Amazing! That's great, and totally works for me. Thank you. Have updated `dfn` mappings accordingly to point to `term` role mappings for all APIs. Closing.
