### ISSUE TITLE
HTML-AAM: MSAA Grouping or Pane for iframe?

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#60]
_From @jasonkiss on September 28, 2016 3:47_

Email from @asurkov: "iframe - same no MSAA role, Firefox exposes a tag name as a role. Maybe we should go with something generic like ROLE_SYSTEM_GROUPING"

The [ROLE_SYSTEM_PANE definition](https://msdn.microsoft.com/en-us/library/windows/desktop/dd373608%28v=vs.85%29.aspx#role_system_pane) is effectively the same as the [Pane Control Type definition](https://msdn.microsoft.com/en-us/library/ee671639%28v=vs.85%29.aspx), which is how UIA maps iframe. What about going with ROLE_SYSTEM_PANE? 

_Copied from original issue: w3c/aria#439_

**Comment by asurkov** [comment]
closing as there's there's no MSAA column and thus there's no need to provide MSAA-only mapping
