### ISSUE TITLE
HTML-AAM: MSAA+IA2 for input types that map to IA2_ROLE_DATE_EDITOR

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#61]
_From @jasonkiss on September 28, 2016 4:12_

Email from @asurkov: 

> input type date - it should be similar to type color input, i.e. 'depends on implementation', so that if the control is implemented a text box, then it should have ROLE_SYSTEM_TEXT role. Also expose text-input-type:date when a text box.
> ....
> same for input type date and time
> ....
> el-input-localdateandtime, el-input-input-month and el-input-week are same as date type

_Copied from original issue: w3c/aria#440_

**Comment by asurkov** [comment]
https://github.com/w3c/html-aam/commit/774293fbf0ef53fb668a0859d9856b3709b86c5c
