### ISSUE TITLE
HTML-AAM: MSAA+IA2 for input type=file

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#62]
_From @jasonkiss on September 28, 2016 5:7_

Email from @asurkov:

> input type file shouldn't list ROLE_SYSTEM_PUSHBUTTON. Otherwise it makes sense to say it's implementation dependent. So in Firefox we always expose a generic accessible for input type file and then button and text accessible for children. If we implemented UIA, then we would do same.

When you say that for UIA you would do the same, do you mean as you currently do in FF, make a generic accessible object with button and text objects as children? Or do you mean you would do the same as what UIA does?

So for MSAA+IA2, do we leave it "Depends on implementation", or do we specify something? Looks like ATK maps to a similar minimum container+children structure. Should MSAA+IA2 follow? What do you suggest?

_Copied from original issue: w3c/aria#441_

**Comment by asurkov** [comment]
On Tue, Oct 11, 2016 at 11:31 PM, Jason Kiss <notifications@github.com>
wrote:

> *From @jasonkiss <https://github.com/jasonkiss> on September 28, 2016 5:7*
>
> Email from @asurkov <https://github.com/asurkov>:
>
> input type file shouldn't list ROLE_SYSTEM_PUSHBUTTON. Otherwise it makes
> sense to say it's implementation dependent. So in Firefox we always expose
> a generic accessible for input type file and then button and text
> accessible for children. If we implemented UIA, then we would do same.
>
> When you say that for UIA you would do the same, do you mean as you
> currently do in FF, make a generic accessible object with button and text
> objects as children?
>
yes


> Or do you mean you would do the same as what UIA does?
>

no, at least this is a real issue breaking the screen readers :)

> So for MSAA+IA2, do we leave it "Depends on implementation", or do we
> specify something?
>
perhaps all platforms should be flexible at this point and say
'implementation dependent'. I think that was my original point.



> Looks like ATK maps to a similar minimum container+children structure.
> Should MSAA+IA2 follow? What do you suggest?
>

ATK mapping looks reasonable, but any changes in MSAA will be not backward
compatible, and we have a real chance to break AT by changing the
implementation. I'm not sure about the best way to proceed.

**Comment by asurkov** [comment]
added a note, that the mapping is implementation dependent, it seems a best thing we can do - https://github.com/w3c/html-aam/commit/a20dbfe265d71aff44b6aa9742a4d6d6dee071da
