### ISSUE TITLE
HTML-AAM: summary exposes expanded/collapsed state in MSAA+IA2

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#64]
_From @jasonkiss on September 28, 2016 5:44_

Email from @asurkov: "summary exposes EXPANDED/COLLAPSED states and actions"

_Copied from original issue: w3c/aria#443_

**Comment by asurkov** [comment]
fixed https://github.com/w3c/html-aam/commit/4d2be0c13695eca77ca25afcc6fd837b4a308585
