### ISSUE TITLE
footer and header element context as landmarks (main element context change from parent to descendant)

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#65]
_From @jongund on May 6, 2016 15:34_

Recommend changing:

"footer (nearest ancestor sectioning content or sectioning root element is not body, or parent is main)"
to
"footer (nearest ancestor sectioning content or sectioning root element is not body or is a descendant of main)"
# 

"footer (nearest ancestor sectioning content or sectioning root element is body)"
to
"footer (nearest ancestor sectioning content or sectioning root element is body and not a descendant of main)"
# 

"header (nearest ancestor sectioning content or sectioning root element is not body, or parent is main)"
to
"header (nearest ancestor sectioning content or sectioning root element is not body or is a descendant of main)"
# 

"header (nearest ancestor sectioning content or sectioning root element is body)"
to
"header (nearest ancestor sectioning content or sectioning root element is body and not a descendant of main)"

_Copied from original issue: w3c/aria#362_

**Comment by jasonkiss** [comment]
Getting the language right here is admittedly tricky. 

I think you're trying to describe a scenario where the `header` or `footer` is not a descendant of `main`, not that the nearest ancestor sectioning element itself is not a descendant of `main`, which is how I read the proposed text. So I don't think the proposed text is exactly right. 

See also issue #277. How would you feel about the following phrase to define the use of `header` and `footer` that should not be landmarks: "descendant of `main`, or of sectioning content or sectioning root element other than `body`"?

Conversely, `header` and `footer` should be landmarks only where they are "descendant of body but not descendant of main or of other sectioning content or sectioning root element".

**Comment by asurkov** [comment]
I'm not sure I clearly understand the wording 'nearest ancestor sectioning content or sectioning root element is body)'. @jasonkiss, could you please explain it, possibly providing some examples?

**Comment by jasonkiss** [comment]
Sorry for the delay, @asurkov. 

Also see [html issue #520](https://github.com/w3c/html/issues/520) in case it helps.

That's the existing language  used in the HTML-AAM, and I think it is not entirely correct in how it describes the `header`/`footer` as landmark scenario. I think that scenario should be written as "nearest ancestor sectioning content or sectioning root element is `body`, and parent is not `main`".

When deciding if a `header` is to be a banner landmark, it all depends on whether or not it is nested within a `main` element, a sectioning content element (`article`, `aside`, `nav`, `section`), or a sectioning root element (`blockquote`, `body`, `details`, `dialog`, `fieldset`, `figure`, `td`). The placement of the `header` in any of those elements defines the scope for the `header`, that is what content it is a header for. Find the `header`'s nearest ancestor that matches one of these elements, and if it is `body`, then it scopes the page as a whole and the `header` is a landmark, and otherwise it is not.

Does the newer language I propose above work better for you?  For example:

- `header` (descendant of `body` but not descendant of `main` or of other sectioning content or sectioning root element) => Maps to banner landmark
- `header` (descendant of `main`, or of sectioning content or sectioning root element other than `body`) => Does not map to banner landmark

**Comment by jasonkiss** [comment]
Closing with https://github.com/w3c/html-aam/commit/d7f6d17d7b9d59dec5c95311844808aed225e593. If wording needs improvement, we can reopen this one.

**Comment by asurkov** [comment]
@jasonkiss thanks for detailed explanation! I filed issue 77 for further possible improvements https://github.com/w3c/html-aam/issues/77
