### ISSUE TITLE
html5 placeholder and aria-placeholder implementation

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aam#69]
The spec currently says:

> When the placeholder and aria-placeholder attributes are both present, and the placeholder attribute's value is non-empty, user agents MUST expose the value of the placeholder attribute, and ignore aria-placeholder. If the placeholder attribute's value is empty, then user agents MUST expose the value of the aria-placeholder attribute.
[https://w3c.github.io/html-aam/#att-placeholder](https://w3c.github.io/html-aam/#att-placeholder)

From [testing](https://dl.dropboxusercontent.com/u/377471/placeholder.html) i carried out over the last week

aria-placeholder as only source of accname:
Firefox = no
edge = yes
safari = yes (in that AXplaceholder value is announced by VO as label)

aria-placeholder="pooter" + placeholder="poot" as only 2 possible sources (placeholder should win)
Firefox = yes
edge = yes
safari = no (aria-placeholder wins)

So in first case Firefox is not following the spec, in second case safari is not.

how should we resolve this? ie. get to a point where behaviour is interoperable and spec reflects this.

ping @alice @cookiecrook @asurkov @boggydigital

**Comment by alice** [comment]
We think that `aria-placeholder` should win, to be consistent with the general principle that `aria-` attributes override native semantics (even if it's an author error to provide both).

**Comment by stevefaulkner** [comment]
> that aria- attributes override native semantics

that's not a general principle (for good or bad) it's that way for label/labelledby/describedby and role values (most) but for others its not.

**Comment by alice** [comment]
Oh I see:

> When a host language declares a WAI-ARIA attribute to be in direct semantic conflict with a native attribute for a given element, user agents must ignore the WAI-ARIA attribute and instead use the host language attribute with the same implicit semantic.

https://www.w3.org/TR/core-aam-1.1/#mapping_conflicts

**Comment by stevefaulkner** [comment]
@alice bingo

**Comment by jasonkiss** [comment]
See related discussion in issue #41. I still have a concern about HTML5 spec recommending against use of `placeholder` to establish label/name for an `input`, then the HTML-AAM codifying the practice as a legitimate option for label/name fallback. Just me?

**Comment by asurkov** [comment]
Here's related discussion on IA2 thread [1]. This is a summary:
1. Expose the placeholder attribute;
2. Keep the current behaviour of falling back to placeholder for name as 
a last resort;
3. When 1) happens, expose explicit-name:false;
4. Don't ever fall back to placeholder for description.

[1] https://lists.linuxfoundation.org/pipermail/accessibility-ia2/2016-September/002152.html

**Comment by stevefaulkner** [comment]
>
>
>    1. Expose the placeholder attribute;
>    2. Keep the current behaviour of falling back to placeholder for name
>    as
>    a last resort;
>    3. When 1) happens, expose explicit-name:false;
>    4. Don't ever fall back to placeholder for description.
>
>
From the perspective of the HTML API spec, which deals with 2 and 4 , the
spec aligns mostly with above.
https://w3c.github.io/html-aam/#att-placeholder
https://w3c.github.io/html-aam/#input-type-text-input-type-password-input-type-search-input-type-tel-input-type-url-and-textarea-element

The difference is that it uses placeholder before using title. thinking
here being is that it placeholder is often used as the only visible label
(despite it not being a best practice)

In regards to the core API spec
http://w3c.github.io/aria/core-aam/core-aam.html#ariaPlaceholder

there is currently no mention of 3

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by cookiecrook** [comment]
I believe the ARIA spec clearly defines that @ placeholder should win over @ aria-placeholder, though I can see the value in letting @ aria-placeholder work if @ placeholder is undefined. (some people don't like the native behavior) I've filed [WebKit bug 165189](https://bugs.webkit.org/show_bug.cgi?id=165189) for update once we reach consensus.

**Comment by richschwer** [comment]
yes, placeholder wins

**Comment by stes-acc** [comment]
I understand that overriding implicit defaults is always matter of discussion.
But:
- Isn't declaring anything be it host language or metadata always overriding implicit behaviour?
- Isn't declaring both of them contradicting an authoring error anyway?

**Comment by jasonkiss** [comment]
Good: `placeholder` wins over `aria-placeholder`. 

Author error or not, if both attributes are present, but `placeholder=""`, is that effectively the same as `placeholder` not being present? Can we get consensus that in this case `aria-placeholder` 'wins'?

**Comment by stevefaulkner** [comment]
declaring `aria-placeholder` on an element that supports `placeholder` is non conforming (an error)
details provided in the issue i  filed on the html conformance checker:
https://github.com/validator/validator/issues/498

**Comment by stes-acc** [comment]
Can the last statement be be generalized for all ARIA attributes/states that have counterparts in the host language?

"declaring  aria-[attribute/state] on an element that supports  [attribute/state] is non conforming (an error) in the conformance checker"

Or are there exceptions?

**Comment by jasonkiss** [comment]
Thanks @stevefaulkner. Closing this issue, but feel free to respond to @stes-acc's question at your leisure :-)

**Comment by lazarljubenovic** [comment]
Interesting. So I cannot use `placeholder` for visual "label", and then use `aria-label` and `aria-required` for better semantics?

```html
<input
  type="email"
  placeholder="Email"
  aria-label="Email"
  aria-placeholder="user@example.com"
>
```

**Comment by stes-acc** [comment]
For they latter is not mapped to accName this should work as additional help if [https://w3c.github.io/core-aam/#ariaPlaceholder](url) remains stable. 

But regarding precedence declaring placeholder vs. aria-placeholder User Agents need precedence rules and not "don't do " authoring rules. Will aria-placeholder win in the Help mapping in this case?

I cannot say that according to everything written above this will be predictable. Any thoughts?

**Comment by lsandler** [comment]
There is this [option](https://developer.paciellogroup.com/blog/2011/02/html5-accessibility-chops-the-placeholder-attribute/) of using regular placeholder but adding styles to improve the text contrast so that it's compliant accessibility wise..  Additionally with this script we are able create title attribute from placeholders globally.. At least when I added the js below my SiteImprove accessibility tester which emulates Chrome okay-ed my placeholders..

`<script>
$(window).load(function() {
//add globally title from placeholder for accessibility
		setTimeout(function () {
			$('input[placeholder]').attr('title', function() {
			  if(!(this.placeholder == null || this.placeholder == ''))  
			  return this.placeholder;
			});
		}, 1000);
});
</script>`
