### ISSUE TITLE
Mappings for @multiple on <input> and <select>

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#72]
Update both @multiple[input] and @multiple[select]. From the looks of things, @multiple[select] should simply map to @aria-multiselectable=true and all platforms use the ARIA mapping. And the mappings for @multiple[input] will likely need to await the outcome of the [ARIA issue #470](https://github.com/w3c/aria/issues/470).

**Comment by scottaohara** [comment]
Appears this issue is stale as the mapping for `select multiple` is in the spec, and ARIA issue 470 resolved with no mapping for `multiple` on `input`.
