### ISSUE TITLE
scripts not working in working draft

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aam#74]
@ylafon the table and details scripts are working in the editors draft, but not in the WD

```
<script src="script/jquery.details.min.js"></script>
<script src="script/mapping-tables.js"></script>
```

any ideas?

**Comment by jasonkiss** [comment]
Looks like same issue we were having previously. See issue #1.

**Comment by jasonkiss** [comment]
There's probably a nicer way to implement it, but it's working now with a single version of mapping-tables.js for both respec and snapshot/WD contexts.
