### ISSUE TITLE
elements table should have 'comments' row

### ISSUE THREAD

**Issue by asurkov** [w3c/html-aam#75]
likewise the attributes table, the elements table would benefit from having 'comments' row, for example, 'summary' element may refer to 'open' attribute on 'details' element.

**Comment by jasonkiss** [comment]
I've often wondered if we should add one to the elements table. But we seemed to be doing fine without it. The comments column in the attributes table seems useful.

I suggest we add it, and then if it's only used for one or two elements, we can look at incorporating those comments into the row some other way, and get rid of the column.

**Comment by jasonkiss** [comment]
Done with https://github.com/w3c/html-aam/commit/52003a6830b1bf02d70202bd91ca4927c72d1600
