### ISSUE TITLE
consider having separate mapping tables for widgets having multiple implementations

### ISSUE THREAD

**Issue by asurkov** [w3c/html-aam#76]
Currently, if the widget exists in multiple implementations then each platform mapping column repeats the wording: "If implemented as textbox then", "if implemented as something then". 

It would be nicer if had something like:

<h_something>a textbox widget</h_something>
<mapping table goes here />
<h_something>a colorpicker widget</h_something>
<mapping table goes here />

**Comment by jasonkiss** [comment]
Not sure I understand what you intend. Can you provide a more detailed example of how you see this being done? Maybe a mockup for an element that has multiple implementations like this?

**Comment by asurkov** [comment]
Now we have something like:

<details>
<summary>input (type attribute in the Number state)</summary>
<table>
<tr><td>MSAA + IAccessible2</td>
<td>If implemented as a spin button, use WAI-ARIA mapping for spinbutton.
If implemented as a text input, use WAI-ARIA mapping for textbox. </td></tr>
<tr><td>UIA	</td>
<td>If implemented as a spin button, use WAI-ARIA mapping for spinbutton.
If implemented as a text input:
Control Type: Edit </td></tr>
</table>
</details>

Instead we could do

<details>
<summary>input (type attribute in the Number state)</summary>

<h2>Represented by a spin button widget</h2>
<table>
<tr><td>IA2</td>
<td>use WAI-ARIA mapping for spinbutton</td></tr>
<tr><td>UIA</td>
<td>use WAI-ARIA mapping for spinbutton</td></tr>
</table>
</table>

<h2>Represented by a textbox widget</h2>
<table>
<tr><td>IA2</td>
<td>use WAI-ARIA mapping for textbox.</td></tr>
<tr><td>UIA</td>
<td>Control Type: Edit </td></tr>
</table>
</table>

</details>

**Comment by jasonkiss** [comment]
How do you see this being represented in the default table markup? Separate rows for each implementation? 

And how do we incorporate APIs/platforms that don't have different implementations (ATK for input@type=color and AX for input@type=number)?

**Comment by asurkov** [comment]
> How do you see this being represented in the default table markup? Separate rows for each implementation?

It is a separate issue, but we might want to consider to change the default table markup. Majority of the browsers support &lt; details &gt; element now, so we can switch the default markup to  &lt; details &gt;. In this case it'd be quite easier to implement the suggestion I think.

If there are no objections why we should stick with existing markup, then I could play with it to check out how easy the transition may be.

> And how do we incorporate APIs/platforms that don't have different implementations (ATK for input@type=color and AX for input@type=number)?

If no implementation exists on a platform, we may keep it missed or say 'n/a'.

**Comment by jasonkiss** [comment]
> If there are no objections why we should stick with existing markup, then I could play with it to check out how easy the transition may be.

I find it quite useful to be able to view the mappings in both table and `details/summary` views. And while I don't think it's necessary that each AAM follow the same markup for mappings, I think it would be important to run this by the other AAMs since they do form something of a suite of specifications.

I could see us keeping the current markup and having separate rows for the different implementations, e.g.

```html
<tr>
     <th>input (type attribute in the Number state and implemented as a spin button)</th>
     <td>...
</tr>
<tr>
     <th>input (type attribute in the Number state and implemented as a text input)</th>
     <td>...
</tr>
```
Ultimately, if you think it's a good change to make, you might want to give it a go in a new branch and share it with the other AAM editors for their input.
