### ISSUE TITLE
make footer and header wording human friendly

### ISSUE THREAD

**Issue by asurkov** [w3c/html-aam#77]
Thanks to @jasonkiss explanations in issue 65 and issue 520 [2] and the original HTML spec, I think I started to understand footer/header wording better, and we could try to improve it to widen the circle of those who understands it :)

I would suggest to replace long descriptions like "footer (nearest ancestor sectioning content or sectioning root element is body and not a descendant of main)" on something simple and refer to the original HTML spec for exact definition. It be good for couple reasons:
* this will improves readability;
* if they make a change in wording, then we don't have to update;
* and they have nice links at terms like 'sectioning content' or 'sectioning root', which we don't have.

What's important for HTML-AAM I think is the mapping depends on whether footer/header is applied to the whole page or not. So I would suggest to use wording like 'footer/header for the whole page' and 'other use cases of footer/header', and refer to HTML spec [3] to define what 'whole page' means aka:

"When the nearest ancestor sectioning content or sectioning root element is the body element, then it applies to the whole page, unless they are descendants of the main element."

How does it sound?

[1] https://github.com/w3c/html-aam/issues/65
[2] https://github.com/w3c/html/issues/520
[3] http://w3c.github.io/html/sections.html#the-header-element

**Comment by jasonkiss** [comment]
@asurkov "other use cases" is a little vague for my liking. I've made some changes in the above commit using "scoped to `body`" and "scoped to the `main` element, a sectioning content element, or a sectioning root element other than body".

I think this is easier to understand than what was there before, while still being precise.

What do you think about these revisions? See http://rawgit.com/w3c/html-aam/gh-pages/index.html#el-footer-ancestorbody

**Comment by asurkov** [comment]
These two options suggest there's a third unnamed/missed option, because it's not evident that "scoped to the main element, a sectioning content element, or a sectioning root element other than body" is equivalent to not "scoped to body". It may be confusing for a spec reader.

 If "others" feels vague, then "not" can be considered, though I like it less. Also we may consider "generic mapping" or "fallback mapping" option pretending it is applied if not overridden above/below.

Also it'd be really nice to refer to HTML spec, in particular this paragraph:

"Assistive Technology may convey the semantics of the header to users when the nearest ancestor sectioning content or sectioning root element is the body element."

I'm not sure how we can do that technically not introducing new definitions in the spec.

**Comment by jasonkiss** [comment]
> These two options suggest there's a third unnamed/missed option, because it's not evident that "scoped to the main element, a sectioning content element, or a sectioning root element other than body" is equivalent to not "scoped to body". It may be confusing for a spec reader.

I agree that a reader might infer a third missing option, but they might do that for a whole range of the elements we list where we distinguish variations, e.g. td (ancestor table element has table role)
 compared to td (ancestor table element has grid role). What about td with ancestor table with some other role? Or what about an input with some other kind of type attribute that's not listed in the mapping table? At some point, I think we have to assume the reader has some familiarity with or will be able to refer to the HTML spec to understand why we've listed the elements we have.

That said, I'd be willing to accept "not scoped to body", but, like you, I like it less.

> Also it'd be really nice to refer to HTML spec, in particular this paragraph:
>
> "Assistive Technology may convey the semantics of the header to users when the nearest ancestor sectioning content or sectioning root element is the body element."
>
> I'm not sure how we can do that technically not introducing new definitions in the spec.

We now have that comment column, so we could put something in there, like "Refer to the [HTML definition for `header`](https://www.w3.org/TR/html/sections.html#the-header-element)" for additional details regarding its scope and importance for assistive technology."

**Comment by jasonkiss** [comment]
Closing for the following reasons:
- the two options, as currently written, accurately describe, with regard to semantic scope and api mapping, the two scenarios in which, by their definitions, `header` or `footer` can find themselves
- there are direct links to the HTML spec definitions for these two elements that explain in more detail

@asurkov Feel free to reopen if you have concerns. Also feel free to include a reference to the HTML spec in the comment column as mentioned in previous comments above.
