### ISSUE TITLE
HTML-AAM:  Unnamed <section> should map as <div>, not unconditionally as role="region"

### ISSUE THREAD

**Issue by klown** [w3c/html-aam#79]
Raising this issue based on comments by myself, @Joanmarie, @mcking65, and @matatk from w3c/aria#513.  

There, the mapping of ARIA role="region" is conditional on the element having an accessible name.  If not, the AAPI role reverts on the native role of the element.

The HTML-AAM unconditionally [maps `<section>`](https://w3c.github.io/html-aam/#el-section) to `region`, except in the case of UIA.  The suggestion in w3c/aria#513 is to map unnamed `<section>` as if it was a `<div>`.

Heads up to @richschwer, since you are reviewing the HTML-AAM.

**Comment by jasonkiss** [comment]
@stevefaulkner, @Joanmarie, @klown As per the commit above, see [revised mappings for `section`](http://rawgit.com/w3c/html-aam/issue-79/index.html#el-section).

Will merge branch if you're happy.

**Comment by klown** [comment]
@jasonkiss Looks good to me.

**Comment by richschwer** [comment]
Please merge this branch. We are writing the test harness and need this to be merged.

**Comment by jasonkiss** [comment]
Merged. https://github.com/w3c/html-aam/commit/2d740ef3a5f70c495d5d1bc8cfc8f88564f1c68a
