### ISSUE TITLE
Incorrect mapping for the picture role and its sub-elements

### ISSUE THREAD

**Issue by richschwer** [w3c/html-aam#81]
As part of html-aam review, we saw that the HTML spec. allows ARIA labelling on the picture element. Consequently picture should map to image whereby name computation should start with the handling aria-label and aria-labelledby on the picture followed by the alt text on the supplied alt text on the embedded fallback img. and very last on the url of the src attribute on the fallback img. The actual fallback image child must not be mapped to an accessible like the other descendants of <picture>.

**Comment by stevefaulkner** [comment]
@richschwer 
from the html spec:

> the picture element itself does not display anything; it merely provides a context for its contained img element that enables it to choose from multiple URLs.

The `picture` element does not itself have any intrinsic semantics and is not considered part of the UI. It is a container for processing instructions for the `img` element. The `img` within the `picture` element is not fallback it is the image. The informative advice about allowed attributes contradicted the normative definition in ARIA in HTML http://w3c.github.io/html-aria/#picture I have updated the HTML spec to reflect the correct information https://github.com/w3c/html/commit/fd3e0654200070f9ec452da0c6fc7a73bdb4030e

**Comment by richschwer** [comment]
OK. removing the global attributes on picture fixes the problem. With that we can focus solely <img>. Thank you.
