### ISSUE TITLE
HTML-AAM: Need standard way to distinguish data tables from layout tables.

### ISSUE THREAD

**Issue by klown** [w3c/html-aam#83]
@cyns raised this as a [Core-AAM 1.1 issue](https://www.w3.org/WAI/ARIA/track/issues/673) in W3C tracker, but noted that it really is an HTML-AAM issue.  I'm moving it here and closing the tracker issue.

Quoting from tracker:

> This belongs in the HTML Accessibility API Mapping doc. I'm not sure which product to use for that, so putting it here where we won't lose it.
> 
> Let's create a standard algorithm for browsers to decide whether to expose a &lt;table&gt; as a table structure in the accessibility API.
> 
> IE implements the UIA table pattern if cell (0,0) is a &lt;th&gt;
> 
> Firefox: 
> http://asurkov.blogspot.co.uk/2011/10/data-vs-layout-table.html
> 
> Chrome:
> https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/accessibility/AXTable.cpp (From a mail thread. I have not read this code)
> 
>

**Comment by mcking65** [comment]
browsers are filtering? sounds dangerous. I thought it is author responsibility to add role presentation to layout tables. If not presentation, then it is exposed. Does it not work this way? Screen readers do filtering, but it can be turned on/off via the screen reader interface, which gives users control. If it is done at the API layer, then users lose ability to see tables that were suppressed but should not have been.

**Comment by stevefaulkner** [comment]
put stuff from html in here about heuristics/algorithms

**Comment by stevefaulkner** [comment]
current advice around this in HTML https://html.spec.whatwg.org/multipage/tables.html#the-table-element

**Comment by scottaohara** [comment]
closing this issue since duplicate #293 now exists
