### ISSUE TITLE
HTML5 placeholder on UIA is inconsistent with ARIA 1.1 aria-placeholder

### ISSUE THREAD

**Issue by richschwer** [w3c/html-aam#87]
Currently, the HTML AAM maps placeholder to the accessible name computation. In no way does the name computation include placeholder. aria-placeholder maps as follows in UIA:

Expose as placeholder=<value> in AriaProperties. 

So, the HTML AAM needs to change the UIA mapping. to refer to the ARIA aria-placeholder mapping for UIA and not the name and description computation document. The ARIA spec. also states that placeholder wins over aria-placeholder when both are present - consistent with the HTML AAM spec.

**Comment by stevefaulkner** [comment]
note: before advent of `aria-placeholder` it was used in accessible name calculation, this is no longer the case.

**Comment by stevefaulkner** [comment]
Filed issues on 

- chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=713600 
- edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11729402/
- added to existing Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1303429
