### ISSUE TITLE
Mapping of tabindex could be interpreted to mean ATK's FOCUSABLE and FOCUSED states are mutually exclusive

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#90]
I was looking into some ARIA 1.1 test failures on my platform in which the failure is that an element lacks `ATK_STATE_FOCUSABLE`.  This struck me as especially odd when the element which lacked the expected ATK_STATE_FOCUSABLE had ATK_STATE_FOCUSED in its state set.

Looking at my platform's mappings for [`tabindex`](https://w3c.github.io/html-aam/#att-tabindex), I see that it says:

    States: `ATK_STATE_FOCUSABLE`; when the element has DOM focus then `ATK_STATE_FOCUSED`

Whether or not the above language is the source of the bug, I don't yet know. However, an implementor could not be blamed for concluding from the above language that these states are mutually exclusive. They are not. An element which can be focused should have ATK_STATE_FOCUSABLE in its state set, regardless of whether or not it happens to be currently focused.

**Comment by jasonkiss** [comment]
Thank you! Fixed in 14b62c8. Closing. Please reopen if change not sufficient.
