### ISSUE TITLE
The 'readonly' attribute should be mapped to ATK_STATE_READ_ONLY

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#93]
The 'readonly' attribute should be mapped to ATK_STATE_READ_ONLY.

**Comment by joanmarie** [comment]
Looking closer, why isn't the attribute mapped to [aria-readonly="true"](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaReadonlyTrue)?

**Comment by jasonkiss** [comment]
Good question. The mappings for aria-readonly=true appear a match for all platforms/APIs but AXAPI. 

Currently the HTML-AAM has AXEnabled: NO for readonly, but "AXValue: the AXUIElementIsAttributeSettable method returns NO" for aria-readonly=true.

AXEnabled:NO seems wrong, and doesn't match what webkit is doing. But I can't confirm if the AXUIElementIsAttributeSettable method returns NO with AXValue. @cookiecrook or @fleizach, are we safe to map HTML `readonly` to aria-readonly="true" where AXAPI is concerned?

**Comment by cookiecrook** [comment]
> are we safe to map HTML readonly to aria-readonly="true" where AXAPI is concerned?

Yes. I believe so.

> AXEnabled:NO seems wrong, and doesn't match what webkit is doing. But I can't confirm if the AXUIElementIsAttributeSettable method returns NO with AXValue.

Yeah, I agree that seems wrong. `AXEnabled` should map inversely to `disabled`/`aria-disabled` rather than `readonly` but perhaps some piece of the chain assumes that readonly is a superset of disabled? @fleizach may know.

**Comment by jasonkiss** [comment]
bb106b9: Have updated all mappings for `readonly` to use CORE-AAM mappings for `aria-readonly=true`. If there are any issues, particularly with AXAPI (ping @fleizach?), can reopen.
