### ISSUE TITLE
MSAA/IA2 completion

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aam#94]
In both the role, and the state and propertey tables, there are a number of ? placeholders in the MSAA + IA2 columns. These need to be updated to include actual data.

**Comment by asurkov** [comment]
I started a thread at IA2 mailing list to clarify those bindings:

https://lists.linuxfoundation.org/pipermail/accessibility-ia2/2017-June/002221.html

**Comment by asurkov** [comment]
fixed by https://github.com/w3c/html-aam/commit/a36747f95c2bad9af28db33c28c8e65365f7ef98
