### ISSUE TITLE
UIA completion

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aam#95]
In both the role, and the state and propertey tables, there are a number of ? placeholders in the UIA columns. These need to be updated to include actual data.

**Comment by boggydigital** [comment]
I've reviewed the existing question marks and will work on the mappings. The direction of the changes would be to use Control Type: "Group"/"Text" (as appropriate for the element), mapping Localized Control Type from the element, consistent with other mappings. While working on that we'll consider any special cases that don't map well to that model.

**Comment by boggydigital** [comment]
Created https://github.com/w3c/html-aam/pull/101

**Comment by jasonkiss** [comment]
The mapping for `meter` is the only ? remaining for UIA, and that mapping is awaiting the outcome of issue #2, so closing this one. Thanks @boggydigital.
