### ISSUE TITLE
ATK/ASPI completion

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aam#96]
In both the role, and the state and propertey tables, there are a number of ? placeholders in the ATK/ASPI columns. These need to be updated to include actual data.

**Comment by jasonkiss** [comment]
Looks like the only entry for ATK with a ? is [`input@multiple`](https://w3c.github.io/html-aam/#att-multiple-input). Based on the other entries, I'm assuming "Not mapped" would be correct here? @joanmarie?

**Comment by joanmarie** [comment]
Right now, we don't really have a corresponding platform attribute or an parallel attribute. Whether or not an AT user would want to know this information is another matter entirely. That said, if all other platforms agree that this is not mapped on their platforms, I'm okay with that for mine.

**Comment by asurkov** [comment]
fyi, no IA2 mapping either [1].

[1] https://lists.linuxfoundation.org/pipermail/accessibility-ia2/2018-January/002228.html

**Comment by joanmarie** [comment]
@jasonkiss and/or @LJWatson: Are you waiting for a specific pull request from me making the change from "?" to "Not mapped"?

**Comment by jasonkiss** [comment]
@joanmarie Thanks, but no :) I've made the change. 

(I also made the same change for AX, as, from what I can tell, it's not mapped there either. Might need @cookiecrook to correct that if wrong.)

Closing on the assumption that we're all good.
