### ISSUE TITLE
AxAPI completion

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aam#97]
In both the role, and the state and propertey tables, there are a number of ? placeholders in the AxAPI columns. These need to be updated to include actual data.

**Comment by jasonkiss** [comment]
Hi @cookiecrook. We're trying to get the HTML-AAM mostly completed for CR, and there are a number of gaps in the AX column that we need help with. Any chance you or someone you can suggest can take a quick stab at it?

The elements table is in good shape and, with the exception of mappings for `meter` which are pending the outcome of issue #2, there's just mappings for `ruby` related elements, as well as the `u` element. I imagine the latter should be "Not mapped" (as probably should the `b`, `i`, `strong`, and `em` elements, which are currently mapped to AXGroup)?

The AX column for the [State and Property mappings](https://w3c.github.io/html-aam/#html-attribute-state-and-property-mappings) has a greater number of gaps:

- [x] - contenteditable
- [x] - coords
- [ ] - datetime
- [x] - dir
- [x] - draggable
- [x] - dropzone
- [x] - height
- [x] - high
- [x] - hreflang
- [x] - label
- [x] - list
- [x] - low
- [x] - maxlength
- [ ] - multiple (on `input`)
- [ ] - pattern
- [ ] - reversed
- [ ] - rows
- [ ] - scope
- [ ] - size
- [ ] - span
- [ ] - spellcheck
- [x] - src
- [x] - start
- [x] - step
- [ ] - tabindex
- [ ] - type
- [ ] - usemap

**Comment by cookiecrook** [comment]
I'm not sure I understand the value of developing this table. It feels like an academic exercise that grossly oversimplifies implementation details (e.g. you can't fit the implementation description of contenteditable neatly into a single table cell). I'm also not sure who the audience for this is, or the value they're expected to gain from it.

**Comment by stevefaulkner** [comment]
@cookiecrook I for one find having some accurate (if incomplete) information available in my job, especially in cases where implementation divergence is evident,  but if you don't find it worthwhile to provide the info I will take a stab at it providing what I can for the missing entries.

**Comment by LJWatson** [comment]
@CookieCrook can you explain a bit more? Is it that you think the information can be better presented in a different format, or that the mapping information is itself not worth documenting, or something else?

**Comment by stevefaulkner** [comment]
@LJWatson have started adding missing info, am checking off as I go
https://github.com/w3c/html-aam/commit/fafa93e02c10ada6ed14039f2e8164ae6299a8b6

**Comment by scottaohara** [comment]
have not checked off items in the previous comment, but I have posted my branch which has updated the tables quite a bit.

remaining attributes to address in my branch are the following:

- [ ]  span
- [ ] spellcheck
- [x] src
- [x] start
- [x] step
- [ ] tabindex
- [ ] type
- [x] usemap
